# coding: utf-8

"""
    TMI (Threat Modeling Improved) API

    A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement 

    The version of the OpenAPI document: 1.2.1
    Contact: api@tmi.local.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictFloat, StrictInt, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from uuid import UUID
from tmi_client.models.cell import Cell
from tmi_client.models.cell_data import CellData
from tmi_client.models.node_all_of_position import NodeAllOfPosition
from tmi_client.models.node_all_of_size import NodeAllOfSize
from tmi_client.models.node_attrs import NodeAttrs
from tmi_client.models.port_configuration import PortConfiguration
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Node(Cell):
    """
    Diagram node representing a process, data store, external entity, or trust boundary
    """ # noqa: E501
    shape: Optional[Annotated[str, Field(strict=True, max_length=1000)]] = Field(default=None, description="Node type determining its visual representation and behavior")
    position: Optional[NodeAllOfPosition] = None
    size: Optional[NodeAllOfSize] = None
    angle: Optional[Union[StrictFloat, StrictInt]] = Field(default=0, description="Rotation angle in degrees")
    attrs: Optional[NodeAttrs] = Field(default=None, description="Visual styling attributes for the node")
    ports: Optional[PortConfiguration] = Field(default=None, description="Port configuration for connections")
    parent: Optional[UUID] = Field(default=None, description="ID of the parent cell for nested/grouped nodes (UUID)")
    children: Optional[Annotated[List[UUID], Field(max_length=1000)]] = Field(default=None, description="IDs of child cells contained within this node (UUIDs)")
    x: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="X coordinate (flat format). Use either this with y, width, height OR use position/size objects.")
    y: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Y coordinate (flat format)")
    width: Optional[Union[Annotated[float, Field(strict=True, ge=40)], Annotated[int, Field(strict=True, ge=40)]]] = Field(default=None, description="Width in pixels (flat format)")
    height: Optional[Union[Annotated[float, Field(strict=True, ge=30)], Annotated[int, Field(strict=True, ge=30)]]] = Field(default=None, description="Height in pixels (flat format)")
    __properties: ClassVar[List[str]] = ["id", "shape", "data", "position", "size", "angle", "attrs", "ports", "parent", "children", "x", "y", "width", "height"]

    @field_validator('shape')
    def shape_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['actor', 'process', 'store', 'security-boundary', 'text-box']):
            raise ValueError("must be one of enum values ('actor', 'process', 'store', 'security-boundary', 'text-box')")
        return value

    @field_validator('parent')
    def parent_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        value = value.isoformat() if hasattr(value, 'isoformat') else str(value)
        if value is None:
            return value

        if not re.match(r"^[0-9a-fA-F]*-[0-9a-fA-F]*-[0-9a-fA-F]*-[0-9a-fA-F]*-[0-9a-fA-F]*$", value):
            raise ValueError(r"must validate the regular expression /^[0-9a-fA-F]*-[0-9a-fA-F]*-[0-9a-fA-F]*-[0-9a-fA-F]*-[0-9a-fA-F]*$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Node from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of position
        if self.position:
            _dict['position'] = self.position.to_dict()
        # override the default output from pydantic by calling `to_dict()` of size
        if self.size:
            _dict['size'] = self.size.to_dict()
        # override the default output from pydantic by calling `to_dict()` of attrs
        if self.attrs:
            _dict['attrs'] = self.attrs.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ports
        if self.ports:
            _dict['ports'] = self.ports.to_dict()
        # set to None if parent (nullable) is None
        # and model_fields_set contains the field
        if self.parent is None and "parent" in self.model_fields_set:
            _dict['parent'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Node from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "shape": obj.get("shape"),
            "data": CellData.from_dict(obj["data"]) if obj.get("data") is not None else None,
            "position": NodeAllOfPosition.from_dict(obj["position"]) if obj.get("position") is not None else None,
            "size": NodeAllOfSize.from_dict(obj["size"]) if obj.get("size") is not None else None,
            "angle": obj.get("angle") if obj.get("angle") is not None else 0,
            "attrs": NodeAttrs.from_dict(obj["attrs"]) if obj.get("attrs") is not None else None,
            "ports": PortConfiguration.from_dict(obj["ports"]) if obj.get("ports") is not None else None,
            "parent": obj.get("parent"),
            "children": obj.get("children"),
            "x": obj.get("x"),
            "y": obj.get("y"),
            "width": obj.get("width"),
            "height": obj.get("height")
        })
        return _obj


