[src]
exclude = ["python-client-generated/v*/", "go-client-generated/v*/", "typescript-client-generated/v*/"]

[rules]
"unresolved-reference" = "ignore"
"unresolved-import" = "ignore"
"unresolved-attribute" = "ignore"
