/*
TMI (Threat Modeling Improved) API

A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement 

API version: 1.4.0
Contact: api@tmi.local.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BaseDiagramInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseDiagramInput{}

// BaseDiagramInput Base diagram input for PUT/PATCH requests - excludes readOnly server-managed fields
type BaseDiagramInput struct {
	// Name of the diagram
	Name string `json:"name" validate:"regexp=^[^<>\\"'&]*$"`
	// Type of diagram with version
	Type string `json:"type"`
	// Key-value pairs for additional diagram metadata
	Metadata []Metadata `json:"metadata,omitempty"`
	Image NullableBaseDiagramImage `json:"image,omitempty"`
	// Optional description of the diagram
	Description NullableString `json:"description,omitempty" validate:"regexp=^[^\\\\x00-\\\\x08\\\\x0B\\\\x0C\\\\x0E-\\\\x1F]*$"`
	// Whether this item should be included in generated reports
	IncludeInReport *bool `json:"include_in_report,omitempty"`
	// Whether the Timmy AI assistant is enabled for this entity
	TimmyEnabled *bool `json:"timmy_enabled,omitempty"`
	// Custom color palette for diagram elements, ordered by position
	ColorPalette []ColorPaletteEntry `json:"color_palette,omitempty"`
}

type _BaseDiagramInput BaseDiagramInput

// NewBaseDiagramInput instantiates a new BaseDiagramInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseDiagramInput(name string, type_ string) *BaseDiagramInput {
	this := BaseDiagramInput{}
	this.Name = name
	this.Type = type_
	var includeInReport bool = true
	this.IncludeInReport = &includeInReport
	var timmyEnabled bool = true
	this.TimmyEnabled = &timmyEnabled
	return &this
}

// NewBaseDiagramInputWithDefaults instantiates a new BaseDiagramInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseDiagramInputWithDefaults() *BaseDiagramInput {
	this := BaseDiagramInput{}
	var includeInReport bool = true
	this.IncludeInReport = &includeInReport
	var timmyEnabled bool = true
	this.TimmyEnabled = &timmyEnabled
	return &this
}

// GetName returns the Name field value
func (o *BaseDiagramInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BaseDiagramInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BaseDiagramInput) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *BaseDiagramInput) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BaseDiagramInput) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BaseDiagramInput) SetType(v string) {
	o.Type = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseDiagramInput) GetMetadata() []Metadata {
	if o == nil {
		var ret []Metadata
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseDiagramInput) GetMetadataOk() ([]Metadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *BaseDiagramInput) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given []Metadata and assigns it to the Metadata field.
func (o *BaseDiagramInput) SetMetadata(v []Metadata) {
	o.Metadata = v
}

// GetImage returns the Image field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseDiagramInput) GetImage() BaseDiagramImage {
	if o == nil || IsNil(o.Image.Get()) {
		var ret BaseDiagramImage
		return ret
	}
	return *o.Image.Get()
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseDiagramInput) GetImageOk() (*BaseDiagramImage, bool) {
	if o == nil {
		return nil, false
	}
	return o.Image.Get(), o.Image.IsSet()
}

// HasImage returns a boolean if a field has been set.
func (o *BaseDiagramInput) HasImage() bool {
	if o != nil && o.Image.IsSet() {
		return true
	}

	return false
}

// SetImage gets a reference to the given NullableBaseDiagramImage and assigns it to the Image field.
func (o *BaseDiagramInput) SetImage(v BaseDiagramImage) {
	o.Image.Set(&v)
}
// SetImageNil sets the value for Image to be an explicit nil
func (o *BaseDiagramInput) SetImageNil() {
	o.Image.Set(nil)
}

// UnsetImage ensures that no value is present for Image, not even an explicit nil
func (o *BaseDiagramInput) UnsetImage() {
	o.Image.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseDiagramInput) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseDiagramInput) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *BaseDiagramInput) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *BaseDiagramInput) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *BaseDiagramInput) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *BaseDiagramInput) UnsetDescription() {
	o.Description.Unset()
}

// GetIncludeInReport returns the IncludeInReport field value if set, zero value otherwise.
func (o *BaseDiagramInput) GetIncludeInReport() bool {
	if o == nil || IsNil(o.IncludeInReport) {
		var ret bool
		return ret
	}
	return *o.IncludeInReport
}

// GetIncludeInReportOk returns a tuple with the IncludeInReport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseDiagramInput) GetIncludeInReportOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeInReport) {
		return nil, false
	}
	return o.IncludeInReport, true
}

// HasIncludeInReport returns a boolean if a field has been set.
func (o *BaseDiagramInput) HasIncludeInReport() bool {
	if o != nil && !IsNil(o.IncludeInReport) {
		return true
	}

	return false
}

// SetIncludeInReport gets a reference to the given bool and assigns it to the IncludeInReport field.
func (o *BaseDiagramInput) SetIncludeInReport(v bool) {
	o.IncludeInReport = &v
}

// GetTimmyEnabled returns the TimmyEnabled field value if set, zero value otherwise.
func (o *BaseDiagramInput) GetTimmyEnabled() bool {
	if o == nil || IsNil(o.TimmyEnabled) {
		var ret bool
		return ret
	}
	return *o.TimmyEnabled
}

// GetTimmyEnabledOk returns a tuple with the TimmyEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseDiagramInput) GetTimmyEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.TimmyEnabled) {
		return nil, false
	}
	return o.TimmyEnabled, true
}

// HasTimmyEnabled returns a boolean if a field has been set.
func (o *BaseDiagramInput) HasTimmyEnabled() bool {
	if o != nil && !IsNil(o.TimmyEnabled) {
		return true
	}

	return false
}

// SetTimmyEnabled gets a reference to the given bool and assigns it to the TimmyEnabled field.
func (o *BaseDiagramInput) SetTimmyEnabled(v bool) {
	o.TimmyEnabled = &v
}

// GetColorPalette returns the ColorPalette field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseDiagramInput) GetColorPalette() []ColorPaletteEntry {
	if o == nil {
		var ret []ColorPaletteEntry
		return ret
	}
	return o.ColorPalette
}

// GetColorPaletteOk returns a tuple with the ColorPalette field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseDiagramInput) GetColorPaletteOk() ([]ColorPaletteEntry, bool) {
	if o == nil || IsNil(o.ColorPalette) {
		return nil, false
	}
	return o.ColorPalette, true
}

// HasColorPalette returns a boolean if a field has been set.
func (o *BaseDiagramInput) HasColorPalette() bool {
	if o != nil && !IsNil(o.ColorPalette) {
		return true
	}

	return false
}

// SetColorPalette gets a reference to the given []ColorPaletteEntry and assigns it to the ColorPalette field.
func (o *BaseDiagramInput) SetColorPalette(v []ColorPaletteEntry) {
	o.ColorPalette = v
}

func (o BaseDiagramInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseDiagramInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Image.IsSet() {
		toSerialize["image"] = o.Image.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.IncludeInReport) {
		toSerialize["include_in_report"] = o.IncludeInReport
	}
	if !IsNil(o.TimmyEnabled) {
		toSerialize["timmy_enabled"] = o.TimmyEnabled
	}
	if o.ColorPalette != nil {
		toSerialize["color_palette"] = o.ColorPalette
	}
	return toSerialize, nil
}

func (o *BaseDiagramInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBaseDiagramInput := _BaseDiagramInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBaseDiagramInput)

	if err != nil {
		return err
	}

	*o = BaseDiagramInput(varBaseDiagramInput)

	return err
}

type NullableBaseDiagramInput struct {
	value *BaseDiagramInput
	isSet bool
}

func (v NullableBaseDiagramInput) Get() *BaseDiagramInput {
	return v.value
}

func (v *NullableBaseDiagramInput) Set(val *BaseDiagramInput) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseDiagramInput) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseDiagramInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseDiagramInput(val *BaseDiagramInput) *NullableBaseDiagramInput {
	return &NullableBaseDiagramInput{value: val, isSet: true}
}

func (v NullableBaseDiagramInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseDiagramInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


