/*
 * TMI (Threat Modeling Improved) API
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package tmiclient

// ModelMap represents a generic map of string keys to any values
type ModelMap = map[string]interface{}
