/*
 * TMI (Threat Modeling Improved) API
 *
 * A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement 
 *
 * API version: 1.3.0
 * Contact: api@tmi.local.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package tmiclient
// ProjectStatus : Project lifecycle status. Defaults to 'active' if not provided or set to null.
type ProjectStatus string

// List of ProjectStatus
const (
	ACTIVE_ProjectStatus ProjectStatus = "active"
	PLANNING_ProjectStatus ProjectStatus = "planning"
	ON_HOLD_ProjectStatus ProjectStatus = "on_hold"
	CANCELLED_ProjectStatus ProjectStatus = "cancelled"
	IN_DEVELOPMENT_ProjectStatus ProjectStatus = "in_development"
	IN_REVIEW_ProjectStatus ProjectStatus = "in_review"
	MVP_ProjectStatus ProjectStatus = "mvp"
	LIMITED_AVAILABILITY_ProjectStatus ProjectStatus = "limited_availability"
	GENERAL_AVAILABILITY_ProjectStatus ProjectStatus = "general_availability"
	DEPRECATED_ProjectStatus ProjectStatus = "deprecated"
	END_OF_LIFE_ProjectStatus ProjectStatus = "end_of_life"
	ARCHIVED_ProjectStatus ProjectStatus = "archived"
)
