/* tslint:disable */
/* eslint-disable */
/**
 * TMI (Threat Modeling Improved) API
 * A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: api@tmi.local.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Group object with administrative fields and enriched data
 * @export
 * @interface AdminGroup
 */
export interface AdminGroup {
    /**
     * Internal system UUID for the group
     * @type {string}
     * @memberof AdminGroup
     */
    internal_uuid: string;
    /**
     * OAuth/SAML provider identifier, or "*" for provider-independent groups
     * @type {string}
     * @memberof AdminGroup
     */
    provider: string;
    /**
     * Provider-assigned group name
     * @type {string}
     * @memberof AdminGroup
     */
    group_name: string;
    /**
     * Human-readable group name
     * @type {string}
     * @memberof AdminGroup
     */
    name?: string;
    /**
     * Group description
     * @type {string}
     * @memberof AdminGroup
     */
    description?: string;
    /**
     * First time this group was referenced
     * @type {Date}
     * @memberof AdminGroup
     */
    first_used: Date;
    /**
     * Last time this group was referenced
     * @type {Date}
     * @memberof AdminGroup
     */
    last_used: Date;
    /**
     * Number of times this group has been referenced
     * @type {number}
     * @memberof AdminGroup
     */
    usage_count: number;
    /**
     * Whether this group is used in any authorizations (enriched)
     * @type {boolean}
     * @memberof AdminGroup
     */
    readonly used_in_authorizations?: boolean;
    /**
     * Whether this group is used in any admin grants (enriched)
     * @type {boolean}
     * @memberof AdminGroup
     */
    readonly used_in_admin_grants?: boolean;
    /**
     * Number of members in the group from IdP (enriched, if available)
     * @type {number}
     * @memberof AdminGroup
     */
    readonly member_count?: number;
}

/**
 * Check if a given object implements the AdminGroup interface.
 */
export function instanceOfAdminGroup(value: object): value is AdminGroup {
    if (!('internal_uuid' in value) || value['internal_uuid'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('group_name' in value) || value['group_name'] === undefined) return false;
    if (!('first_used' in value) || value['first_used'] === undefined) return false;
    if (!('last_used' in value) || value['last_used'] === undefined) return false;
    if (!('usage_count' in value) || value['usage_count'] === undefined) return false;
    return true;
}

export function AdminGroupFromJSON(json: any): AdminGroup {
    return AdminGroupFromJSONTyped(json, false);
}

export function AdminGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'internal_uuid': json['internal_uuid'],
        'provider': json['provider'],
        'group_name': json['group_name'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'first_used': (new Date(json['first_used'])),
        'last_used': (new Date(json['last_used'])),
        'usage_count': json['usage_count'],
        'used_in_authorizations': json['used_in_authorizations'] == null ? undefined : json['used_in_authorizations'],
        'used_in_admin_grants': json['used_in_admin_grants'] == null ? undefined : json['used_in_admin_grants'],
        'member_count': json['member_count'] == null ? undefined : json['member_count'],
    };
}

export function AdminGroupToJSON(json: any): AdminGroup {
    return AdminGroupToJSONTyped(json, false);
}

export function AdminGroupToJSONTyped(value?: Omit<AdminGroup, 'used_in_authorizations'|'used_in_admin_grants'|'member_count'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'internal_uuid': value['internal_uuid'],
        'provider': value['provider'],
        'group_name': value['group_name'],
        'name': value['name'],
        'description': value['description'],
        'first_used': value['first_used'].toISOString(),
        'last_used': value['last_used'].toISOString(),
        'usage_count': value['usage_count'],
    };
}

