/*
 * TMI (Threat Modeling Improved) API
 * A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement 
 *
 * OpenAPI spec version: 1.2.0
 * Contact: api@tmi.local.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CreateAdminGroupRequest model module.
 * @module model/CreateAdminGroupRequest
 * @version 1.0.0
 */
export default class CreateAdminGroupRequest {
  /**
   * Constructs a new <code>CreateAdminGroupRequest</code>.
   * Request body for creating a provider-independent group
   * @alias module:model/CreateAdminGroupRequest
   * @class
   * @param groupName {String} Group identifier (alphanumeric, hyphens, underscores only)
   * @param name {String} Human-readable group name
   */
  constructor(groupName, name) {
    this.groupName = groupName;
    this.name = name;
  }

  /**
   * Constructs a <code>CreateAdminGroupRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateAdminGroupRequest} obj Optional instance to populate.
   * @return {module:model/CreateAdminGroupRequest} The populated <code>CreateAdminGroupRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateAdminGroupRequest();
      if (data.hasOwnProperty('group_name'))
        obj.groupName = ApiClient.convertToType(data['group_name'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * Group identifier (alphanumeric, hyphens, underscores only)
 * @member {String} groupName
 */
CreateAdminGroupRequest.prototype.groupName = undefined;

/**
 * Human-readable group name
 * @member {String} name
 */
CreateAdminGroupRequest.prototype.name = undefined;

/**
 * Optional group description
 * @member {String} description
 */
CreateAdminGroupRequest.prototype.description = undefined;

