/*
 * TMI (Threat Modeling Improved) API
 * A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement 
 *
 * OpenAPI spec version: 1.2.0
 * Contact: api@tmi.local.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Authorization from './Authorization';

/**
 * The SurveyResponseBase model module.
 * @module model/SurveyResponseBase
 * @version 1.0.0
 */
export default class SurveyResponseBase {
  /**
   * Constructs a new <code>SurveyResponseBase</code>.
   * Base schema for SurveyResponse with client-writable fields
   * @alias module:model/SurveyResponseBase
   * @class
   * @param surveyId {String} ID of the survey this response is based on
   */
  constructor(surveyId) {
    this.surveyId = surveyId;
  }

  /**
   * Constructs a <code>SurveyResponseBase</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SurveyResponseBase} obj Optional instance to populate.
   * @return {module:model/SurveyResponseBase} The populated <code>SurveyResponseBase</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SurveyResponseBase();
      if (data.hasOwnProperty('answers'))
        obj.answers = ApiClient.convertToType(data['answers'], {'String': Object});
      if (data.hasOwnProperty('linked_threat_model_id'))
        obj.linkedThreatModelId = ApiClient.convertToType(data['linked_threat_model_id'], 'String');
      if (data.hasOwnProperty('authorization'))
        obj.authorization = ApiClient.convertToType(data['authorization'], [Authorization]);
      if (data.hasOwnProperty('ui_state'))
        obj.uiState = ApiClient.convertToType(data['ui_state'], {'String': Object});
      if (data.hasOwnProperty('survey_id'))
        obj.surveyId = ApiClient.convertToType(data['survey_id'], 'String');
      if (data.hasOwnProperty('survey_version'))
        obj.surveyVersion = ApiClient.convertToType(data['survey_version'], 'String');
      if (data.hasOwnProperty('project_id'))
        obj.projectId = ApiClient.convertToType(data['project_id'], 'String');
    }
    return obj;
  }
}

/**
 * Question answers keyed by question name. Values can be any JSON type to support all SurveyJS question types including dynamic panels (arrays of objects), matrix questions (objects of objects), and scalar values (strings, numbers, booleans).
 * @member {Object.<String, Object>} answers
 */
SurveyResponseBase.prototype.answers = undefined;

/**
 * Optional link to existing threat model for re-reviews
 * @member {String} linkedThreatModelId
 */
SurveyResponseBase.prototype.linkedThreatModelId = undefined;

/**
 * List of users and groups with access to this response
 * @member {Array.<module:model/Authorization>} authorization
 */
SurveyResponseBase.prototype.authorization = undefined;

/**
 * Client-managed UI state for draft resumption (e.g., current page, scroll position). Cleared on submission.
 * @member {Object.<String, Object>} uiState
 */
SurveyResponseBase.prototype.uiState = undefined;

/**
 * ID of the survey this response is based on
 * @member {String} surveyId
 */
SurveyResponseBase.prototype.surveyId = undefined;

/**
 * Survey version captured at creation time - responses always complete on the original version
 * @member {String} surveyVersion
 */
SurveyResponseBase.prototype.surveyVersion = undefined;

/**
 * Optional reference to the project this survey response belongs to
 * @member {String} projectId
 */
SurveyResponseBase.prototype.projectId = undefined;

