/*
 * TMI (Threat Modeling Improved) API
 * A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement 
 *
 * OpenAPI spec version: 1.2.0
 * Contact: api@tmi.local.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Metadata from './Metadata';
import SurveyBase from './SurveyBase';
import SurveySettings from './SurveySettings';

/**
 * The Survey model module.
 * @module model/Survey
 * @version 1.0.0
 */
export default class Survey extends SurveyBase {
  /**
   * Constructs a new <code>Survey</code>.
   * A survey defining questions for security review intake
   * @alias module:model/Survey
   * @class
   * @extends module:model/SurveyBase
   * @param name {} Name of the survey
   * @param version {} Custom version string (e.g., '2024-Q1', 'v2-pilot')
   * @param surveyJson {} Complete SurveyJS JSON definition. Opaque to the server; validated only for top-level structure (must contain a pages array).
   */
  constructor(name, version, surveyJson) {
    super(name, version, surveyJson);
  }

  /**
   * Constructs a <code>Survey</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Survey} obj Optional instance to populate.
   * @return {module:model/Survey} The populated <code>Survey</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Survey();
      SurveyBase.constructFromObject(data, obj);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'Date');
      if (data.hasOwnProperty('modified_at'))
        obj.modifiedAt = ApiClient.convertToType(data['modified_at'], 'Date');
      if (data.hasOwnProperty('created_by'))
        obj.createdBy = ApiClient.convertToType(data['created_by'], Object);
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], [Metadata]);
    }
    return obj;
  }
}

/**
 * Unique identifier for the survey (UUID)
 * @member {String} id
 */
Survey.prototype.id = undefined;

/**
 * Creation timestamp (RFC3339)
 * @member {Date} createdAt
 */
Survey.prototype.createdAt = undefined;

/**
 * Last modification timestamp (RFC3339)
 * @member {Date} modifiedAt
 */
Survey.prototype.modifiedAt = undefined;

/**
 * Administrator who created the survey
 * @member {Object} createdBy
 */
Survey.prototype.createdBy = undefined;

/**
 * Optional metadata key-value pairs
 * @member {Array.<module:model/Metadata>} metadata
 */
Survey.prototype.metadata = undefined;

