/* tslint:disable */
/* eslint-disable */
/**
 * TMI (Threat Modeling Improved) API
 * A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: eric@tmi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  BulkPatchRequest,
  JsonPatchDocumentInner,
  ListProjectsResponse,
  Metadata,
  Project,
  ProjectBase,
  RelationshipType,
} from "../models/index";
import {
  BulkPatchRequestFromJSON,
  BulkPatchRequestToJSON,
  JsonPatchDocumentInnerFromJSON,
  JsonPatchDocumentInnerToJSON,
  ListProjectsResponseFromJSON,
  ListProjectsResponseToJSON,
  MetadataFromJSON,
  MetadataToJSON,
  ProjectFromJSON,
  ProjectToJSON,
  ProjectBaseFromJSON,
  ProjectBaseToJSON,
  RelationshipTypeFromJSON,
  RelationshipTypeToJSON,
} from "../models/index";

export interface BulkCreateProjectMetadataRequest {
  projectId: string;
  metadata: Array<Metadata>;
}

export interface BulkReplaceProjectMetadataRequest {
  projectId: string;
  metadata: Array<Metadata>;
}

export interface BulkUpsertProjectMetadataRequest {
  projectId: string;
  bulkPatchRequest: BulkPatchRequest;
}

export interface CreateProjectRequest {
  body: ProjectBase;
}

export interface CreateProjectMetadataRequest {
  projectId: string;
  metadata: Metadata;
}

export interface DeleteProjectRequest {
  projectId: string;
}

export interface DeleteProjectMetadataRequest {
  projectId: string;
  key: string;
}

export interface GetProjectRequest {
  projectId: string;
}

export interface GetProjectMetadataRequest {
  projectId: string;
}

export interface ListProjectsRequest {
  limit?: number;
  offset?: number;
  name?: string;
  status?: string;
  teamId?: string;
  relatedTo?: string;
  relationship?: RelationshipType;
  transitive?: boolean;
}

export interface PatchProjectRequest {
  projectId: string;
  jsonPatchDocumentInner: Array<JsonPatchDocumentInner>;
}

export interface UpdateProjectRequest {
  projectId: string;
  body: ProjectBase;
}

export interface UpdateProjectMetadataRequest {
  projectId: string;
  key: string;
  metadata: Metadata;
}

/**
 * ProjectsApi - interface
 *
 * @export
 * @interface ProjectsApiInterface
 */
export interface ProjectsApiInterface {
  /**
   * Creates request options for bulkCreateProjectMetadata without sending the request
   * @param {string} projectId Project identifier (UUID)
   * @param {Array<Metadata>} metadata Bulk metadata entries to create
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  bulkCreateProjectMetadataRequestOpts(
    requestParameters: BulkCreateProjectMetadataRequest,
  ): Promise<runtime.RequestOpts>;

  /**
   * Create multiple metadata key-value pairs for the specified project in a single request.
   * @summary Bulk create project metadata
   * @param {string} projectId Project identifier (UUID)
   * @param {Array<Metadata>} metadata Bulk metadata entries to create
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  bulkCreateProjectMetadataRaw(
    requestParameters: BulkCreateProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Metadata>>>;

  /**
   * Create multiple metadata key-value pairs for the specified project in a single request.
   * Bulk create project metadata
   */
  bulkCreateProjectMetadata(
    requestParameters: BulkCreateProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Metadata>>;

  /**
   * Creates request options for bulkReplaceProjectMetadata without sending the request
   * @param {string} projectId Project identifier (UUID)
   * @param {Array<Metadata>} metadata Complete set of metadata entries for replacement
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  bulkReplaceProjectMetadataRequestOpts(
    requestParameters: BulkReplaceProjectMetadataRequest,
  ): Promise<runtime.RequestOpts>;

  /**
   * Replace all metadata for the specified project with the provided key-value pairs.
   * @summary Bulk replace project metadata
   * @param {string} projectId Project identifier (UUID)
   * @param {Array<Metadata>} metadata Complete set of metadata entries for replacement
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  bulkReplaceProjectMetadataRaw(
    requestParameters: BulkReplaceProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Metadata>>>;

  /**
   * Replace all metadata for the specified project with the provided key-value pairs.
   * Bulk replace project metadata
   */
  bulkReplaceProjectMetadata(
    requestParameters: BulkReplaceProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Metadata>>;

  /**
   * Creates request options for bulkUpsertProjectMetadata without sending the request
   * @param {string} projectId Project identifier (UUID)
   * @param {BulkPatchRequest} bulkPatchRequest Metadata entries to update
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  bulkUpsertProjectMetadataRequestOpts(
    requestParameters: BulkUpsertProjectMetadataRequest,
  ): Promise<runtime.RequestOpts>;

  /**
   * Create or update multiple metadata key-value pairs for the specified project in a single request.
   * @summary Bulk upsert project metadata
   * @param {string} projectId Project identifier (UUID)
   * @param {BulkPatchRequest} bulkPatchRequest Metadata entries to update
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  bulkUpsertProjectMetadataRaw(
    requestParameters: BulkUpsertProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Metadata>>>;

  /**
   * Create or update multiple metadata key-value pairs for the specified project in a single request.
   * Bulk upsert project metadata
   */
  bulkUpsertProjectMetadata(
    requestParameters: BulkUpsertProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Metadata>>;

  /**
   * Creates request options for createProject without sending the request
   * @param {ProjectBase} body Project creation data
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  createProjectRequestOpts(
    requestParameters: CreateProjectRequest,
  ): Promise<runtime.RequestOpts>;

  /**
   * Creates a new project. Requires membership in the referenced team.
   * @summary Create a project
   * @param {ProjectBase} body Project creation data
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  createProjectRaw(
    requestParameters: CreateProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Project>>;

  /**
   * Creates a new project. Requires membership in the referenced team.
   * Create a project
   */
  createProject(
    requestParameters: CreateProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Project>;

  /**
   * Creates request options for createProjectMetadata without sending the request
   * @param {string} projectId Project identifier (UUID)
   * @param {Metadata} metadata Metadata entry to create
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  createProjectMetadataRequestOpts(
    requestParameters: CreateProjectMetadataRequest,
  ): Promise<runtime.RequestOpts>;

  /**
   * Create a new metadata key-value pair for the specified project.
   * @summary Create project metadata
   * @param {string} projectId Project identifier (UUID)
   * @param {Metadata} metadata Metadata entry to create
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  createProjectMetadataRaw(
    requestParameters: CreateProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Metadata>>;

  /**
   * Create a new metadata key-value pair for the specified project.
   * Create project metadata
   */
  createProjectMetadata(
    requestParameters: CreateProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Metadata>;

  /**
   * Creates request options for deleteProject without sending the request
   * @param {string} projectId Project UUID
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  deleteProjectRequestOpts(
    requestParameters: DeleteProjectRequest,
  ): Promise<runtime.RequestOpts>;

  /**
   * Deletes a project. Requires owner role or admin access. Returns 409 if the project is referenced by threat models.
   * @summary Delete a project
   * @param {string} projectId Project UUID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  deleteProjectRaw(
    requestParameters: DeleteProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   * Deletes a project. Requires owner role or admin access. Returns 409 if the project is referenced by threat models.
   * Delete a project
   */
  deleteProject(
    requestParameters: DeleteProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;

  /**
   * Creates request options for deleteProjectMetadata without sending the request
   * @param {string} projectId Project identifier (UUID)
   * @param {string} key Metadata key
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  deleteProjectMetadataRequestOpts(
    requestParameters: DeleteProjectMetadataRequest,
  ): Promise<runtime.RequestOpts>;

  /**
   * Delete a metadata key-value pair from the specified project.
   * @summary Delete project metadata
   * @param {string} projectId Project identifier (UUID)
   * @param {string} key Metadata key
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  deleteProjectMetadataRaw(
    requestParameters: DeleteProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   * Delete a metadata key-value pair from the specified project.
   * Delete project metadata
   */
  deleteProjectMetadata(
    requestParameters: DeleteProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;

  /**
   * Creates request options for getProject without sending the request
   * @param {string} projectId Project UUID
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  getProjectRequestOpts(
    requestParameters: GetProjectRequest,
  ): Promise<runtime.RequestOpts>;

  /**
   * Returns a project by ID. Requires membership in the project\'s team or admin access.
   * @summary Get a project
   * @param {string} projectId Project UUID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  getProjectRaw(
    requestParameters: GetProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Project>>;

  /**
   * Returns a project by ID. Requires membership in the project\'s team or admin access.
   * Get a project
   */
  getProject(
    requestParameters: GetProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Project>;

  /**
   * Creates request options for getProjectMetadata without sending the request
   * @param {string} projectId Project identifier (UUID)
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  getProjectMetadataRequestOpts(
    requestParameters: GetProjectMetadataRequest,
  ): Promise<runtime.RequestOpts>;

  /**
   * Retrieve all metadata key-value pairs associated with the specified project.
   * @summary Get project metadata
   * @param {string} projectId Project identifier (UUID)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  getProjectMetadataRaw(
    requestParameters: GetProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Metadata>>>;

  /**
   * Retrieve all metadata key-value pairs associated with the specified project.
   * Get project metadata
   */
  getProjectMetadata(
    requestParameters: GetProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Metadata>>;

  /**
   * Creates request options for listProjects without sending the request
   * @param {number} [limit] Maximum number of results per page
   * @param {number} [offset] Number of results to skip
   * @param {string} [name] Filter by project name (partial match)
   * @param {string} [status] Filter by status (exact match, comma-separated for multiple)
   * @param {string} [teamId] Filter by team
   * @param {string} [relatedTo] Include projects related to this project ID
   * @param {RelationshipType} [relationship] Filter related projects by relationship type. Only used with related_to.
   * @param {boolean} [transitive] When true with related_to + relationship, follow parent/child chains transitively (max depth 10)
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  listProjectsRequestOpts(
    requestParameters: ListProjectsRequest,
  ): Promise<runtime.RequestOpts>;

  /**
   * Returns a paginated list of projects. Non-admin users see only projects belonging to teams they are members of.
   * @summary List projects
   * @param {number} [limit] Maximum number of results per page
   * @param {number} [offset] Number of results to skip
   * @param {string} [name] Filter by project name (partial match)
   * @param {string} [status] Filter by status (exact match, comma-separated for multiple)
   * @param {string} [teamId] Filter by team
   * @param {string} [relatedTo] Include projects related to this project ID
   * @param {RelationshipType} [relationship] Filter related projects by relationship type. Only used with related_to.
   * @param {boolean} [transitive] When true with related_to + relationship, follow parent/child chains transitively (max depth 10)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  listProjectsRaw(
    requestParameters: ListProjectsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListProjectsResponse>>;

  /**
   * Returns a paginated list of projects. Non-admin users see only projects belonging to teams they are members of.
   * List projects
   */
  listProjects(
    requestParameters: ListProjectsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListProjectsResponse>;

  /**
   * Creates request options for patchProject without sending the request
   * @param {string} projectId Project UUID
   * @param {Array<JsonPatchDocumentInner>} jsonPatchDocumentInner Partial project data for update
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  patchProjectRequestOpts(
    requestParameters: PatchProjectRequest,
  ): Promise<runtime.RequestOpts>;

  /**
   * Partial update of a project using JSON Patch (RFC 6902). Requires membership in the project\'s team or admin access.
   * @summary Patch a project
   * @param {string} projectId Project UUID
   * @param {Array<JsonPatchDocumentInner>} jsonPatchDocumentInner Partial project data for update
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  patchProjectRaw(
    requestParameters: PatchProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Project>>;

  /**
   * Partial update of a project using JSON Patch (RFC 6902). Requires membership in the project\'s team or admin access.
   * Patch a project
   */
  patchProject(
    requestParameters: PatchProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Project>;

  /**
   * Creates request options for updateProject without sending the request
   * @param {string} projectId Project UUID
   * @param {ProjectBase} body Complete project data for replacement
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  updateProjectRequestOpts(
    requestParameters: UpdateProjectRequest,
  ): Promise<runtime.RequestOpts>;

  /**
   * Full replacement update of a project. Requires membership in the project\'s team or admin access.
   * @summary Update a project
   * @param {string} projectId Project UUID
   * @param {ProjectBase} body Complete project data for replacement
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  updateProjectRaw(
    requestParameters: UpdateProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Project>>;

  /**
   * Full replacement update of a project. Requires membership in the project\'s team or admin access.
   * Update a project
   */
  updateProject(
    requestParameters: UpdateProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Project>;

  /**
   * Creates request options for updateProjectMetadata without sending the request
   * @param {string} projectId Project identifier (UUID)
   * @param {string} key Metadata key
   * @param {Metadata} metadata Metadata value to set for the specified key
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  updateProjectMetadataRequestOpts(
    requestParameters: UpdateProjectMetadataRequest,
  ): Promise<runtime.RequestOpts>;

  /**
   * Update the value of an existing metadata key for the specified project.
   * @summary Update project metadata
   * @param {string} projectId Project identifier (UUID)
   * @param {string} key Metadata key
   * @param {Metadata} metadata Metadata value to set for the specified key
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProjectsApiInterface
   */
  updateProjectMetadataRaw(
    requestParameters: UpdateProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Metadata>>;

  /**
   * Update the value of an existing metadata key for the specified project.
   * Update project metadata
   */
  updateProjectMetadata(
    requestParameters: UpdateProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Metadata>;
}

/**
 *
 */
export class ProjectsApi
  extends runtime.BaseAPI
  implements ProjectsApiInterface
{
  /**
   * Creates request options for bulkCreateProjectMetadata without sending the request
   */
  async bulkCreateProjectMetadataRequestOpts(
    requestParameters: BulkCreateProjectMetadataRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError(
        "projectId",
        'Required parameter "projectId" was null or undefined when calling bulkCreateProjectMetadata().',
      );
    }

    if (requestParameters["metadata"] == null) {
      throw new runtime.RequiredError(
        "metadata",
        'Required parameter "metadata" was null or undefined when calling bulkCreateProjectMetadata().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/projects/{project_id}/metadata/bulk`;
    urlPath = urlPath.replace(
      `{${"project_id"}}`,
      encodeURIComponent(String(requestParameters["projectId"])),
    );

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters["metadata"]!.map(MetadataToJSON),
    };
  }

  /**
   * Create multiple metadata key-value pairs for the specified project in a single request.
   * Bulk create project metadata
   */
  async bulkCreateProjectMetadataRaw(
    requestParameters: BulkCreateProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Metadata>>> {
    const requestOptions =
      await this.bulkCreateProjectMetadataRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(MetadataFromJSON),
    );
  }

  /**
   * Create multiple metadata key-value pairs for the specified project in a single request.
   * Bulk create project metadata
   */
  async bulkCreateProjectMetadata(
    requestParameters: BulkCreateProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Metadata>> {
    const response = await this.bulkCreateProjectMetadataRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for bulkReplaceProjectMetadata without sending the request
   */
  async bulkReplaceProjectMetadataRequestOpts(
    requestParameters: BulkReplaceProjectMetadataRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError(
        "projectId",
        'Required parameter "projectId" was null or undefined when calling bulkReplaceProjectMetadata().',
      );
    }

    if (requestParameters["metadata"] == null) {
      throw new runtime.RequiredError(
        "metadata",
        'Required parameter "metadata" was null or undefined when calling bulkReplaceProjectMetadata().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/projects/{project_id}/metadata/bulk`;
    urlPath = urlPath.replace(
      `{${"project_id"}}`,
      encodeURIComponent(String(requestParameters["projectId"])),
    );

    return {
      path: urlPath,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters["metadata"]!.map(MetadataToJSON),
    };
  }

  /**
   * Replace all metadata for the specified project with the provided key-value pairs.
   * Bulk replace project metadata
   */
  async bulkReplaceProjectMetadataRaw(
    requestParameters: BulkReplaceProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Metadata>>> {
    const requestOptions =
      await this.bulkReplaceProjectMetadataRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(MetadataFromJSON),
    );
  }

  /**
   * Replace all metadata for the specified project with the provided key-value pairs.
   * Bulk replace project metadata
   */
  async bulkReplaceProjectMetadata(
    requestParameters: BulkReplaceProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Metadata>> {
    const response = await this.bulkReplaceProjectMetadataRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for bulkUpsertProjectMetadata without sending the request
   */
  async bulkUpsertProjectMetadataRequestOpts(
    requestParameters: BulkUpsertProjectMetadataRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError(
        "projectId",
        'Required parameter "projectId" was null or undefined when calling bulkUpsertProjectMetadata().',
      );
    }

    if (requestParameters["bulkPatchRequest"] == null) {
      throw new runtime.RequiredError(
        "bulkPatchRequest",
        'Required parameter "bulkPatchRequest" was null or undefined when calling bulkUpsertProjectMetadata().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/projects/{project_id}/metadata/bulk`;
    urlPath = urlPath.replace(
      `{${"project_id"}}`,
      encodeURIComponent(String(requestParameters["projectId"])),
    );

    return {
      path: urlPath,
      method: "PATCH",
      headers: headerParameters,
      query: queryParameters,
      body: BulkPatchRequestToJSON(requestParameters["bulkPatchRequest"]),
    };
  }

  /**
   * Create or update multiple metadata key-value pairs for the specified project in a single request.
   * Bulk upsert project metadata
   */
  async bulkUpsertProjectMetadataRaw(
    requestParameters: BulkUpsertProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Metadata>>> {
    const requestOptions =
      await this.bulkUpsertProjectMetadataRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(MetadataFromJSON),
    );
  }

  /**
   * Create or update multiple metadata key-value pairs for the specified project in a single request.
   * Bulk upsert project metadata
   */
  async bulkUpsertProjectMetadata(
    requestParameters: BulkUpsertProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Metadata>> {
    const response = await this.bulkUpsertProjectMetadataRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for createProject without sending the request
   */
  async createProjectRequestOpts(
    requestParameters: CreateProjectRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["body"] == null) {
      throw new runtime.RequiredError(
        "body",
        'Required parameter "body" was null or undefined when calling createProject().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/projects`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters["body"] as any,
    };
  }

  /**
   * Creates a new project. Requires membership in the referenced team.
   * Create a project
   */
  async createProjectRaw(
    requestParameters: CreateProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Project>> {
    const requestOptions =
      await this.createProjectRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProjectFromJSON(jsonValue),
    );
  }

  /**
   * Creates a new project. Requires membership in the referenced team.
   * Create a project
   */
  async createProject(
    requestParameters: CreateProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Project> {
    const response = await this.createProjectRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for createProjectMetadata without sending the request
   */
  async createProjectMetadataRequestOpts(
    requestParameters: CreateProjectMetadataRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError(
        "projectId",
        'Required parameter "projectId" was null or undefined when calling createProjectMetadata().',
      );
    }

    if (requestParameters["metadata"] == null) {
      throw new runtime.RequiredError(
        "metadata",
        'Required parameter "metadata" was null or undefined when calling createProjectMetadata().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/projects/{project_id}/metadata`;
    urlPath = urlPath.replace(
      `{${"project_id"}}`,
      encodeURIComponent(String(requestParameters["projectId"])),
    );

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: MetadataToJSON(requestParameters["metadata"]),
    };
  }

  /**
   * Create a new metadata key-value pair for the specified project.
   * Create project metadata
   */
  async createProjectMetadataRaw(
    requestParameters: CreateProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Metadata>> {
    const requestOptions =
      await this.createProjectMetadataRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      MetadataFromJSON(jsonValue),
    );
  }

  /**
   * Create a new metadata key-value pair for the specified project.
   * Create project metadata
   */
  async createProjectMetadata(
    requestParameters: CreateProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Metadata> {
    const response = await this.createProjectMetadataRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for deleteProject without sending the request
   */
  async deleteProjectRequestOpts(
    requestParameters: DeleteProjectRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError(
        "projectId",
        'Required parameter "projectId" was null or undefined when calling deleteProject().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/projects/{project_id}`;
    urlPath = urlPath.replace(
      `{${"project_id"}}`,
      encodeURIComponent(String(requestParameters["projectId"])),
    );

    return {
      path: urlPath,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Deletes a project. Requires owner role or admin access. Returns 409 if the project is referenced by threat models.
   * Delete a project
   */
  async deleteProjectRaw(
    requestParameters: DeleteProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.deleteProjectRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Deletes a project. Requires owner role or admin access. Returns 409 if the project is referenced by threat models.
   * Delete a project
   */
  async deleteProject(
    requestParameters: DeleteProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteProjectRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for deleteProjectMetadata without sending the request
   */
  async deleteProjectMetadataRequestOpts(
    requestParameters: DeleteProjectMetadataRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError(
        "projectId",
        'Required parameter "projectId" was null or undefined when calling deleteProjectMetadata().',
      );
    }

    if (requestParameters["key"] == null) {
      throw new runtime.RequiredError(
        "key",
        'Required parameter "key" was null or undefined when calling deleteProjectMetadata().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/projects/{project_id}/metadata/{key}`;
    urlPath = urlPath.replace(
      `{${"project_id"}}`,
      encodeURIComponent(String(requestParameters["projectId"])),
    );
    urlPath = urlPath.replace(
      `{${"key"}}`,
      encodeURIComponent(String(requestParameters["key"])),
    );

    return {
      path: urlPath,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Delete a metadata key-value pair from the specified project.
   * Delete project metadata
   */
  async deleteProjectMetadataRaw(
    requestParameters: DeleteProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.deleteProjectMetadataRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete a metadata key-value pair from the specified project.
   * Delete project metadata
   */
  async deleteProjectMetadata(
    requestParameters: DeleteProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteProjectMetadataRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for getProject without sending the request
   */
  async getProjectRequestOpts(
    requestParameters: GetProjectRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError(
        "projectId",
        'Required parameter "projectId" was null or undefined when calling getProject().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/projects/{project_id}`;
    urlPath = urlPath.replace(
      `{${"project_id"}}`,
      encodeURIComponent(String(requestParameters["projectId"])),
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns a project by ID. Requires membership in the project\'s team or admin access.
   * Get a project
   */
  async getProjectRaw(
    requestParameters: GetProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Project>> {
    const requestOptions = await this.getProjectRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProjectFromJSON(jsonValue),
    );
  }

  /**
   * Returns a project by ID. Requires membership in the project\'s team or admin access.
   * Get a project
   */
  async getProject(
    requestParameters: GetProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Project> {
    const response = await this.getProjectRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getProjectMetadata without sending the request
   */
  async getProjectMetadataRequestOpts(
    requestParameters: GetProjectMetadataRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError(
        "projectId",
        'Required parameter "projectId" was null or undefined when calling getProjectMetadata().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/projects/{project_id}/metadata`;
    urlPath = urlPath.replace(
      `{${"project_id"}}`,
      encodeURIComponent(String(requestParameters["projectId"])),
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Retrieve all metadata key-value pairs associated with the specified project.
   * Get project metadata
   */
  async getProjectMetadataRaw(
    requestParameters: GetProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Metadata>>> {
    const requestOptions =
      await this.getProjectMetadataRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(MetadataFromJSON),
    );
  }

  /**
   * Retrieve all metadata key-value pairs associated with the specified project.
   * Get project metadata
   */
  async getProjectMetadata(
    requestParameters: GetProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Metadata>> {
    const response = await this.getProjectMetadataRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for listProjects without sending the request
   */
  async listProjectsRequestOpts(
    requestParameters: ListProjectsRequest,
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    if (requestParameters["name"] != null) {
      queryParameters["name"] = requestParameters["name"];
    }

    if (requestParameters["status"] != null) {
      queryParameters["status"] = requestParameters["status"];
    }

    if (requestParameters["teamId"] != null) {
      queryParameters["team_id"] = requestParameters["teamId"];
    }

    if (requestParameters["relatedTo"] != null) {
      queryParameters["related_to"] = requestParameters["relatedTo"];
    }

    if (requestParameters["relationship"] != null) {
      queryParameters["relationship"] = requestParameters["relationship"];
    }

    if (requestParameters["transitive"] != null) {
      queryParameters["transitive"] = requestParameters["transitive"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/projects`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns a paginated list of projects. Non-admin users see only projects belonging to teams they are members of.
   * List projects
   */
  async listProjectsRaw(
    requestParameters: ListProjectsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListProjectsResponse>> {
    const requestOptions =
      await this.listProjectsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListProjectsResponseFromJSON(jsonValue),
    );
  }

  /**
   * Returns a paginated list of projects. Non-admin users see only projects belonging to teams they are members of.
   * List projects
   */
  async listProjects(
    requestParameters: ListProjectsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListProjectsResponse> {
    const response = await this.listProjectsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for patchProject without sending the request
   */
  async patchProjectRequestOpts(
    requestParameters: PatchProjectRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError(
        "projectId",
        'Required parameter "projectId" was null or undefined when calling patchProject().',
      );
    }

    if (requestParameters["jsonPatchDocumentInner"] == null) {
      throw new runtime.RequiredError(
        "jsonPatchDocumentInner",
        'Required parameter "jsonPatchDocumentInner" was null or undefined when calling patchProject().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json-patch+json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/projects/{project_id}`;
    urlPath = urlPath.replace(
      `{${"project_id"}}`,
      encodeURIComponent(String(requestParameters["projectId"])),
    );

    return {
      path: urlPath,
      method: "PATCH",
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters["jsonPatchDocumentInner"]!.map(
        JsonPatchDocumentInnerToJSON,
      ),
    };
  }

  /**
   * Partial update of a project using JSON Patch (RFC 6902). Requires membership in the project\'s team or admin access.
   * Patch a project
   */
  async patchProjectRaw(
    requestParameters: PatchProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Project>> {
    const requestOptions =
      await this.patchProjectRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProjectFromJSON(jsonValue),
    );
  }

  /**
   * Partial update of a project using JSON Patch (RFC 6902). Requires membership in the project\'s team or admin access.
   * Patch a project
   */
  async patchProject(
    requestParameters: PatchProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Project> {
    const response = await this.patchProjectRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for updateProject without sending the request
   */
  async updateProjectRequestOpts(
    requestParameters: UpdateProjectRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError(
        "projectId",
        'Required parameter "projectId" was null or undefined when calling updateProject().',
      );
    }

    if (requestParameters["body"] == null) {
      throw new runtime.RequiredError(
        "body",
        'Required parameter "body" was null or undefined when calling updateProject().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/projects/{project_id}`;
    urlPath = urlPath.replace(
      `{${"project_id"}}`,
      encodeURIComponent(String(requestParameters["projectId"])),
    );

    return {
      path: urlPath,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters["body"] as any,
    };
  }

  /**
   * Full replacement update of a project. Requires membership in the project\'s team or admin access.
   * Update a project
   */
  async updateProjectRaw(
    requestParameters: UpdateProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Project>> {
    const requestOptions =
      await this.updateProjectRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProjectFromJSON(jsonValue),
    );
  }

  /**
   * Full replacement update of a project. Requires membership in the project\'s team or admin access.
   * Update a project
   */
  async updateProject(
    requestParameters: UpdateProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Project> {
    const response = await this.updateProjectRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates request options for updateProjectMetadata without sending the request
   */
  async updateProjectMetadataRequestOpts(
    requestParameters: UpdateProjectMetadataRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["projectId"] == null) {
      throw new runtime.RequiredError(
        "projectId",
        'Required parameter "projectId" was null or undefined when calling updateProjectMetadata().',
      );
    }

    if (requestParameters["key"] == null) {
      throw new runtime.RequiredError(
        "key",
        'Required parameter "key" was null or undefined when calling updateProjectMetadata().',
      );
    }

    if (requestParameters["metadata"] == null) {
      throw new runtime.RequiredError(
        "metadata",
        'Required parameter "metadata" was null or undefined when calling updateProjectMetadata().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/projects/{project_id}/metadata/{key}`;
    urlPath = urlPath.replace(
      `{${"project_id"}}`,
      encodeURIComponent(String(requestParameters["projectId"])),
    );
    urlPath = urlPath.replace(
      `{${"key"}}`,
      encodeURIComponent(String(requestParameters["key"])),
    );

    return {
      path: urlPath,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: MetadataToJSON(requestParameters["metadata"]),
    };
  }

  /**
   * Update the value of an existing metadata key for the specified project.
   * Update project metadata
   */
  async updateProjectMetadataRaw(
    requestParameters: UpdateProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Metadata>> {
    const requestOptions =
      await this.updateProjectMetadataRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      MetadataFromJSON(jsonValue),
    );
  }

  /**
   * Update the value of an existing metadata key for the specified project.
   * Update project metadata
   */
  async updateProjectMetadata(
    requestParameters: UpdateProjectMetadataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Metadata> {
    const response = await this.updateProjectMetadataRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
