/*
 * TMI (Threat Modeling Improved) API
 * A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement 
 *
 * OpenAPI spec version: 1.2.0
 * Contact: api@tmi.local.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import BulkPatchRequest from '../model/BulkPatchRequest';
import Error from '../model/Error';
import JsonPatchDocumentInner from '../model/JsonPatchDocumentInner';
import ListProjectsResponse from '../model/ListProjectsResponse';
import Metadata from '../model/Metadata';
import Project from '../model/Project';
import ProjectBase from '../model/ProjectBase';
import RelationshipType from '../model/RelationshipType';

/**
* Projects service.
* @module api/ProjectsApi
* @version 1.0.0
*/
export default class ProjectsApi {

    /**
    * Constructs a new ProjectsApi. 
    * @alias module:api/ProjectsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Bulk create project metadata
     * @param {Array.<module:model/Metadata>} body Bulk metadata entries to create
     * @param {String} projectId Project identifier (UUID)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Metadata>} and HTTP response
     */
    bulkCreateProjectMetadataWithHttpInfo(body, projectId) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling bulkCreateProjectMetadata");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling bulkCreateProjectMetadata");
      }

      let pathParams = {
        'project_id': projectId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [Metadata];

      return this.apiClient.callApi(
        '/projects/{project_id}/metadata/bulk', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Bulk create project metadata
     * @param {<&vendorExtensions.x-jsdoc-type>} body Bulk metadata entries to create
     * @param {<&vendorExtensions.x-jsdoc-type>} projectId Project identifier (UUID)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Metadata>}
     */
    bulkCreateProjectMetadata(body, projectId) {
      return this.bulkCreateProjectMetadataWithHttpInfo(body, projectId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Bulk replace project metadata
     * @param {Array.<module:model/Metadata>} body Complete set of metadata entries for replacement
     * @param {String} projectId Project identifier (UUID)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Metadata>} and HTTP response
     */
    bulkReplaceProjectMetadataWithHttpInfo(body, projectId) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling bulkReplaceProjectMetadata");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling bulkReplaceProjectMetadata");
      }

      let pathParams = {
        'project_id': projectId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [Metadata];

      return this.apiClient.callApi(
        '/projects/{project_id}/metadata/bulk', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Bulk replace project metadata
     * @param {<&vendorExtensions.x-jsdoc-type>} body Complete set of metadata entries for replacement
     * @param {<&vendorExtensions.x-jsdoc-type>} projectId Project identifier (UUID)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Metadata>}
     */
    bulkReplaceProjectMetadata(body, projectId) {
      return this.bulkReplaceProjectMetadataWithHttpInfo(body, projectId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Bulk upsert project metadata
     * @param {module:model/BulkPatchRequest} body Metadata entries to update
     * @param {String} projectId Project identifier (UUID)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Metadata>} and HTTP response
     */
    bulkUpsertProjectMetadataWithHttpInfo(body, projectId) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling bulkUpsertProjectMetadata");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling bulkUpsertProjectMetadata");
      }

      let pathParams = {
        'project_id': projectId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [Metadata];

      return this.apiClient.callApi(
        '/projects/{project_id}/metadata/bulk', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Bulk upsert project metadata
     * @param {<&vendorExtensions.x-jsdoc-type>} body Metadata entries to update
     * @param {<&vendorExtensions.x-jsdoc-type>} projectId Project identifier (UUID)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Metadata>}
     */
    bulkUpsertProjectMetadata(body, projectId) {
      return this.bulkUpsertProjectMetadataWithHttpInfo(body, projectId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a project
     * Creates a new project. Requires membership in the referenced team.
     * @param {module:model/ProjectBase} body Project creation data
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Project} and HTTP response
     */
    createProjectWithHttpInfo(body) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createProject");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Project;

      return this.apiClient.callApi(
        '/projects', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Create a project
     * Creates a new project. Requires membership in the referenced team.
     * @param {<&vendorExtensions.x-jsdoc-type>} body Project creation data
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Project}
     */
    createProject(body) {
      return this.createProjectWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create project metadata
     * @param {module:model/Metadata} body Metadata entry to create
     * @param {String} projectId Project identifier (UUID)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Metadata} and HTTP response
     */
    createProjectMetadataWithHttpInfo(body, projectId) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createProjectMetadata");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling createProjectMetadata");
      }

      let pathParams = {
        'project_id': projectId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Metadata;

      return this.apiClient.callApi(
        '/projects/{project_id}/metadata', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Create project metadata
     * @param {<&vendorExtensions.x-jsdoc-type>} body Metadata entry to create
     * @param {<&vendorExtensions.x-jsdoc-type>} projectId Project identifier (UUID)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Metadata}
     */
    createProjectMetadata(body, projectId) {
      return this.createProjectMetadataWithHttpInfo(body, projectId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete a project
     * Deletes a project. Requires owner role or admin access. Returns 409 if the project is referenced by threat models.
     * @param {String} projectId Project UUID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteProjectWithHttpInfo(projectId) {
      
      let postBody = null;
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling deleteProject");
      }

      let pathParams = {
        'project_id': projectId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/projects/{project_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Delete a project
     * Deletes a project. Requires owner role or admin access. Returns 409 if the project is referenced by threat models.
     * @param {<&vendorExtensions.x-jsdoc-type>} projectId Project UUID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteProject(projectId) {
      return this.deleteProjectWithHttpInfo(projectId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete project metadata
     * @param {String} projectId Project identifier (UUID)
     * @param {String} key Metadata key
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteProjectMetadataWithHttpInfo(projectId, key) {
      
      let postBody = null;
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling deleteProjectMetadata");
      }
      // verify the required parameter 'key' is set
      if (key === undefined || key === null) {
        throw new Error("Missing the required parameter 'key' when calling deleteProjectMetadata");
      }

      let pathParams = {
        'project_id': projectId,'key': key
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/projects/{project_id}/metadata/{key}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Delete project metadata
     * @param {<&vendorExtensions.x-jsdoc-type>} projectId Project identifier (UUID)
     * @param {<&vendorExtensions.x-jsdoc-type>} key Metadata key
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteProjectMetadata(projectId, key) {
      return this.deleteProjectMetadataWithHttpInfo(projectId, key)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a project
     * Returns a project by ID. Requires membership in the project&#x27;s team or admin access.
     * @param {String} projectId Project UUID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Project} and HTTP response
     */
    getProjectWithHttpInfo(projectId) {
      
      let postBody = null;
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling getProject");
      }

      let pathParams = {
        'project_id': projectId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Project;

      return this.apiClient.callApi(
        '/projects/{project_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get a project
     * Returns a project by ID. Requires membership in the project&#x27;s team or admin access.
     * @param {<&vendorExtensions.x-jsdoc-type>} projectId Project UUID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Project}
     */
    getProject(projectId) {
      return this.getProjectWithHttpInfo(projectId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get project metadata
     * @param {String} projectId Project identifier (UUID)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Metadata>} and HTTP response
     */
    getProjectMetadataWithHttpInfo(projectId) {
      
      let postBody = null;
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling getProjectMetadata");
      }

      let pathParams = {
        'project_id': projectId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Metadata];

      return this.apiClient.callApi(
        '/projects/{project_id}/metadata', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get project metadata
     * @param {<&vendorExtensions.x-jsdoc-type>} projectId Project identifier (UUID)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Metadata>}
     */
    getProjectMetadata(projectId) {
      return this.getProjectMetadataWithHttpInfo(projectId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List projects
     * Returns a paginated list of projects. Non-admin users see only projects belonging to teams they are members of.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Maximum number of results per page (default to <.>)
     * @param {Number} opts.offset Number of results to skip (default to <.>)
     * @param {String} opts.name Filter by project name (partial match)
     * @param {String} opts.status Filter by status (exact match, comma-separated for multiple)
     * @param {String} opts.teamId Filter by team
     * @param {String} opts.relatedTo Include projects related to this project ID
     * @param {module:model/RelationshipType} opts.relationship Filter related projects by relationship type. Only used with related_to.
     * @param {Boolean} opts.transitive When true with related_to + relationship, follow parent/child chains transitively (max depth 10) (default to <.>)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListProjectsResponse} and HTTP response
     */
    listProjectsWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'limit': opts['limit'],'offset': opts['offset'],'name': opts['name'],'status': opts['status'],'team_id': opts['teamId'],'related_to': opts['relatedTo'],'relationship': opts['relationship'],'transitive': opts['transitive']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListProjectsResponse;

      return this.apiClient.callApi(
        '/projects', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * List projects
     * Returns a paginated list of projects. Non-admin users see only projects belonging to teams they are members of.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Maximum number of results per page (default to <.>)
     * @param {Number} opts.offset Number of results to skip (default to <.>)
     * @param {String} opts.name Filter by project name (partial match)
     * @param {String} opts.status Filter by status (exact match, comma-separated for multiple)
     * @param {String} opts.teamId Filter by team
     * @param {String} opts.relatedTo Include projects related to this project ID
     * @param {module:model/RelationshipType} opts.relationship Filter related projects by relationship type. Only used with related_to.
     * @param {Boolean} opts.transitive When true with related_to + relationship, follow parent/child chains transitively (max depth 10) (default to <.>)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListProjectsResponse}
     */
    listProjects(opts) {
      return this.listProjectsWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Patch a project
     * Partial update of a project using JSON Patch (RFC 6902). Requires membership in the project&#x27;s team or admin access.
     * @param {Array.<module:model/JsonPatchDocumentInner>} body Partial project data for update
     * @param {String} projectId Project UUID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Project} and HTTP response
     */
    patchProjectWithHttpInfo(body, projectId) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling patchProject");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling patchProject");
      }

      let pathParams = {
        'project_id': projectId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json-patch+json'];
      let accepts = ['application/json'];
      let returnType = Project;

      return this.apiClient.callApi(
        '/projects/{project_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Patch a project
     * Partial update of a project using JSON Patch (RFC 6902). Requires membership in the project&#x27;s team or admin access.
     * @param {<&vendorExtensions.x-jsdoc-type>} body Partial project data for update
     * @param {<&vendorExtensions.x-jsdoc-type>} projectId Project UUID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Project}
     */
    patchProject(body, projectId) {
      return this.patchProjectWithHttpInfo(body, projectId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update a project
     * Full replacement update of a project. Requires membership in the project&#x27;s team or admin access.
     * @param {module:model/ProjectBase} body Complete project data for replacement
     * @param {String} projectId Project UUID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Project} and HTTP response
     */
    updateProjectWithHttpInfo(body, projectId) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateProject");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling updateProject");
      }

      let pathParams = {
        'project_id': projectId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Project;

      return this.apiClient.callApi(
        '/projects/{project_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Update a project
     * Full replacement update of a project. Requires membership in the project&#x27;s team or admin access.
     * @param {<&vendorExtensions.x-jsdoc-type>} body Complete project data for replacement
     * @param {<&vendorExtensions.x-jsdoc-type>} projectId Project UUID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Project}
     */
    updateProject(body, projectId) {
      return this.updateProjectWithHttpInfo(body, projectId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update project metadata
     * @param {module:model/Metadata} body Metadata value to set for the specified key
     * @param {String} projectId Project identifier (UUID)
     * @param {String} key Metadata key
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Metadata} and HTTP response
     */
    updateProjectMetadataWithHttpInfo(body, projectId, key) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateProjectMetadata");
      }
      // verify the required parameter 'projectId' is set
      if (projectId === undefined || projectId === null) {
        throw new Error("Missing the required parameter 'projectId' when calling updateProjectMetadata");
      }
      // verify the required parameter 'key' is set
      if (key === undefined || key === null) {
        throw new Error("Missing the required parameter 'key' when calling updateProjectMetadata");
      }

      let pathParams = {
        'project_id': projectId,'key': key
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Metadata;

      return this.apiClient.callApi(
        '/projects/{project_id}/metadata/{key}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Update project metadata
     * @param {<&vendorExtensions.x-jsdoc-type>} body Metadata value to set for the specified key
     * @param {<&vendorExtensions.x-jsdoc-type>} projectId Project identifier (UUID)
     * @param {<&vendorExtensions.x-jsdoc-type>} key Metadata key
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Metadata}
     */
    updateProjectMetadata(body, projectId, key) {
      return this.updateProjectMetadataWithHttpInfo(body, projectId, key)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }

}