/*
TMI (Threat Modeling Improved) API

A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement 

API version: 1.2.1
Contact: api@tmi.local.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ThreatBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThreatBase{}

// ThreatBase Base schema for Threat with client-writable fields
type ThreatBase struct {
	// Name of the threat
	Name string `json:"name" validate:"regexp=^[^<>\\"'&]*$"`
	// Description of the threat and risk to the organization
	Description *string `json:"description,omitempty" validate:"regexp=^[^<>\\\\x00-\\\\x08\\\\x0B\\\\x0C\\\\x0E-\\\\x1F]*$"`
	// Recommended or planned mitigation(s) for the threat
	Mitigation *string `json:"mitigation,omitempty" validate:"regexp=^[^\\\\x00-\\\\x08\\\\x0B\\\\x0C\\\\x0E-\\\\x1F]*$"`
	// Unique identifier of the associated diagram (if applicable) (UUID)
	DiagramId NullableString `json:"diagram_id,omitempty" validate:"regexp=^[0-9a-fA-F]*-[0-9a-fA-F]*-[0-9a-fA-F]*-[0-9a-fA-F]*-[0-9a-fA-F]*$"`
	// Unique identifier of the associated cell (if applicable) (UUID)
	CellId NullableString `json:"cell_id,omitempty" validate:"regexp=^[0-9a-fA-F]*-[0-9a-fA-F]*-[0-9a-fA-F]*-[0-9a-fA-F]*-[0-9a-fA-F]*$"`
	// Severity level of the threat
	Severity *string `json:"severity,omitempty" validate:"regexp=^[^\\\\x00-\\\\x1F]*$"`
	// Numeric score representing the risk or impact of the threat
	Score *float32 `json:"score,omitempty"`
	// Priority level for addressing the threat
	Priority *string `json:"priority,omitempty" validate:"regexp=^[^\\\\x00-\\\\x1F]*$"`
	// Whether the threat has been mitigated
	Mitigated *bool `json:"mitigated,omitempty"`
	// Current status of the threat
	Status *string `json:"status,omitempty" validate:"regexp=^[^\\\\x00-\\\\x1F]*$"`
	// Types or categories of the threat. Supports multiple classifications within the same framework (e.g., ['Spoofing', 'Tampering']). Empty array indicates no types assigned.
	ThreatType []string `json:"threat_type"`
	// Key-value pairs for additional threat metadata
	Metadata []Metadata `json:"metadata,omitempty"`
	// URL to an issue in an issue tracking system for this threat
	IssueUri *string `json:"issue_uri,omitempty" validate:"regexp=^\\\\s*https?:\\/\\/[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\\\\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*(:[0-9]{1,5})?(\\/[^\\\\s]*)?\\\\s*$"`
	// Unique identifier of the associated asset (if applicable) (UUID)
	AssetId NullableString `json:"asset_id,omitempty" validate:"regexp=^[0-9a-fA-F]*-[0-9a-fA-F]*-[0-9a-fA-F]*-[0-9a-fA-F]*-[0-9a-fA-F]*$"`
	// CWE (Common Weakness Enumeration) identifiers associated with this threat
	CweId []string `json:"cwe_id,omitempty"`
	// CVSS scoring information for this threat
	Cvss []CVSSScore `json:"cvss,omitempty"`
	// Whether this item should be included in generated reports
	IncludeInReport *bool `json:"include_in_report,omitempty"`
}

type _ThreatBase ThreatBase

// NewThreatBase instantiates a new ThreatBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThreatBase(name string, threatType []string) *ThreatBase {
	this := ThreatBase{}
	this.Name = name
	this.ThreatType = threatType
	var includeInReport bool = true
	this.IncludeInReport = &includeInReport
	return &this
}

// NewThreatBaseWithDefaults instantiates a new ThreatBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThreatBaseWithDefaults() *ThreatBase {
	this := ThreatBase{}
	var includeInReport bool = true
	this.IncludeInReport = &includeInReport
	return &this
}

// GetName returns the Name field value
func (o *ThreatBase) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ThreatBase) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ThreatBase) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ThreatBase) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatBase) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ThreatBase) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ThreatBase) SetDescription(v string) {
	o.Description = &v
}

// GetMitigation returns the Mitigation field value if set, zero value otherwise.
func (o *ThreatBase) GetMitigation() string {
	if o == nil || IsNil(o.Mitigation) {
		var ret string
		return ret
	}
	return *o.Mitigation
}

// GetMitigationOk returns a tuple with the Mitigation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatBase) GetMitigationOk() (*string, bool) {
	if o == nil || IsNil(o.Mitigation) {
		return nil, false
	}
	return o.Mitigation, true
}

// HasMitigation returns a boolean if a field has been set.
func (o *ThreatBase) HasMitigation() bool {
	if o != nil && !IsNil(o.Mitigation) {
		return true
	}

	return false
}

// SetMitigation gets a reference to the given string and assigns it to the Mitigation field.
func (o *ThreatBase) SetMitigation(v string) {
	o.Mitigation = &v
}

// GetDiagramId returns the DiagramId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ThreatBase) GetDiagramId() string {
	if o == nil || IsNil(o.DiagramId.Get()) {
		var ret string
		return ret
	}
	return *o.DiagramId.Get()
}

// GetDiagramIdOk returns a tuple with the DiagramId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ThreatBase) GetDiagramIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DiagramId.Get(), o.DiagramId.IsSet()
}

// HasDiagramId returns a boolean if a field has been set.
func (o *ThreatBase) HasDiagramId() bool {
	if o != nil && o.DiagramId.IsSet() {
		return true
	}

	return false
}

// SetDiagramId gets a reference to the given NullableString and assigns it to the DiagramId field.
func (o *ThreatBase) SetDiagramId(v string) {
	o.DiagramId.Set(&v)
}
// SetDiagramIdNil sets the value for DiagramId to be an explicit nil
func (o *ThreatBase) SetDiagramIdNil() {
	o.DiagramId.Set(nil)
}

// UnsetDiagramId ensures that no value is present for DiagramId, not even an explicit nil
func (o *ThreatBase) UnsetDiagramId() {
	o.DiagramId.Unset()
}

// GetCellId returns the CellId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ThreatBase) GetCellId() string {
	if o == nil || IsNil(o.CellId.Get()) {
		var ret string
		return ret
	}
	return *o.CellId.Get()
}

// GetCellIdOk returns a tuple with the CellId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ThreatBase) GetCellIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CellId.Get(), o.CellId.IsSet()
}

// HasCellId returns a boolean if a field has been set.
func (o *ThreatBase) HasCellId() bool {
	if o != nil && o.CellId.IsSet() {
		return true
	}

	return false
}

// SetCellId gets a reference to the given NullableString and assigns it to the CellId field.
func (o *ThreatBase) SetCellId(v string) {
	o.CellId.Set(&v)
}
// SetCellIdNil sets the value for CellId to be an explicit nil
func (o *ThreatBase) SetCellIdNil() {
	o.CellId.Set(nil)
}

// UnsetCellId ensures that no value is present for CellId, not even an explicit nil
func (o *ThreatBase) UnsetCellId() {
	o.CellId.Unset()
}

// GetSeverity returns the Severity field value if set, zero value otherwise.
func (o *ThreatBase) GetSeverity() string {
	if o == nil || IsNil(o.Severity) {
		var ret string
		return ret
	}
	return *o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatBase) GetSeverityOk() (*string, bool) {
	if o == nil || IsNil(o.Severity) {
		return nil, false
	}
	return o.Severity, true
}

// HasSeverity returns a boolean if a field has been set.
func (o *ThreatBase) HasSeverity() bool {
	if o != nil && !IsNil(o.Severity) {
		return true
	}

	return false
}

// SetSeverity gets a reference to the given string and assigns it to the Severity field.
func (o *ThreatBase) SetSeverity(v string) {
	o.Severity = &v
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *ThreatBase) GetScore() float32 {
	if o == nil || IsNil(o.Score) {
		var ret float32
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatBase) GetScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *ThreatBase) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given float32 and assigns it to the Score field.
func (o *ThreatBase) SetScore(v float32) {
	o.Score = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *ThreatBase) GetPriority() string {
	if o == nil || IsNil(o.Priority) {
		var ret string
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatBase) GetPriorityOk() (*string, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *ThreatBase) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given string and assigns it to the Priority field.
func (o *ThreatBase) SetPriority(v string) {
	o.Priority = &v
}

// GetMitigated returns the Mitigated field value if set, zero value otherwise.
func (o *ThreatBase) GetMitigated() bool {
	if o == nil || IsNil(o.Mitigated) {
		var ret bool
		return ret
	}
	return *o.Mitigated
}

// GetMitigatedOk returns a tuple with the Mitigated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatBase) GetMitigatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Mitigated) {
		return nil, false
	}
	return o.Mitigated, true
}

// HasMitigated returns a boolean if a field has been set.
func (o *ThreatBase) HasMitigated() bool {
	if o != nil && !IsNil(o.Mitigated) {
		return true
	}

	return false
}

// SetMitigated gets a reference to the given bool and assigns it to the Mitigated field.
func (o *ThreatBase) SetMitigated(v bool) {
	o.Mitigated = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ThreatBase) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatBase) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ThreatBase) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ThreatBase) SetStatus(v string) {
	o.Status = &v
}

// GetThreatType returns the ThreatType field value
func (o *ThreatBase) GetThreatType() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ThreatType
}

// GetThreatTypeOk returns a tuple with the ThreatType field value
// and a boolean to check if the value has been set.
func (o *ThreatBase) GetThreatTypeOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ThreatType, true
}

// SetThreatType sets field value
func (o *ThreatBase) SetThreatType(v []string) {
	o.ThreatType = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ThreatBase) GetMetadata() []Metadata {
	if o == nil {
		var ret []Metadata
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ThreatBase) GetMetadataOk() ([]Metadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ThreatBase) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given []Metadata and assigns it to the Metadata field.
func (o *ThreatBase) SetMetadata(v []Metadata) {
	o.Metadata = v
}

// GetIssueUri returns the IssueUri field value if set, zero value otherwise.
func (o *ThreatBase) GetIssueUri() string {
	if o == nil || IsNil(o.IssueUri) {
		var ret string
		return ret
	}
	return *o.IssueUri
}

// GetIssueUriOk returns a tuple with the IssueUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatBase) GetIssueUriOk() (*string, bool) {
	if o == nil || IsNil(o.IssueUri) {
		return nil, false
	}
	return o.IssueUri, true
}

// HasIssueUri returns a boolean if a field has been set.
func (o *ThreatBase) HasIssueUri() bool {
	if o != nil && !IsNil(o.IssueUri) {
		return true
	}

	return false
}

// SetIssueUri gets a reference to the given string and assigns it to the IssueUri field.
func (o *ThreatBase) SetIssueUri(v string) {
	o.IssueUri = &v
}

// GetAssetId returns the AssetId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ThreatBase) GetAssetId() string {
	if o == nil || IsNil(o.AssetId.Get()) {
		var ret string
		return ret
	}
	return *o.AssetId.Get()
}

// GetAssetIdOk returns a tuple with the AssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ThreatBase) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssetId.Get(), o.AssetId.IsSet()
}

// HasAssetId returns a boolean if a field has been set.
func (o *ThreatBase) HasAssetId() bool {
	if o != nil && o.AssetId.IsSet() {
		return true
	}

	return false
}

// SetAssetId gets a reference to the given NullableString and assigns it to the AssetId field.
func (o *ThreatBase) SetAssetId(v string) {
	o.AssetId.Set(&v)
}
// SetAssetIdNil sets the value for AssetId to be an explicit nil
func (o *ThreatBase) SetAssetIdNil() {
	o.AssetId.Set(nil)
}

// UnsetAssetId ensures that no value is present for AssetId, not even an explicit nil
func (o *ThreatBase) UnsetAssetId() {
	o.AssetId.Unset()
}

// GetCweId returns the CweId field value if set, zero value otherwise.
func (o *ThreatBase) GetCweId() []string {
	if o == nil || IsNil(o.CweId) {
		var ret []string
		return ret
	}
	return o.CweId
}

// GetCweIdOk returns a tuple with the CweId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatBase) GetCweIdOk() ([]string, bool) {
	if o == nil || IsNil(o.CweId) {
		return nil, false
	}
	return o.CweId, true
}

// HasCweId returns a boolean if a field has been set.
func (o *ThreatBase) HasCweId() bool {
	if o != nil && !IsNil(o.CweId) {
		return true
	}

	return false
}

// SetCweId gets a reference to the given []string and assigns it to the CweId field.
func (o *ThreatBase) SetCweId(v []string) {
	o.CweId = v
}

// GetCvss returns the Cvss field value if set, zero value otherwise.
func (o *ThreatBase) GetCvss() []CVSSScore {
	if o == nil || IsNil(o.Cvss) {
		var ret []CVSSScore
		return ret
	}
	return o.Cvss
}

// GetCvssOk returns a tuple with the Cvss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatBase) GetCvssOk() ([]CVSSScore, bool) {
	if o == nil || IsNil(o.Cvss) {
		return nil, false
	}
	return o.Cvss, true
}

// HasCvss returns a boolean if a field has been set.
func (o *ThreatBase) HasCvss() bool {
	if o != nil && !IsNil(o.Cvss) {
		return true
	}

	return false
}

// SetCvss gets a reference to the given []CVSSScore and assigns it to the Cvss field.
func (o *ThreatBase) SetCvss(v []CVSSScore) {
	o.Cvss = v
}

// GetIncludeInReport returns the IncludeInReport field value if set, zero value otherwise.
func (o *ThreatBase) GetIncludeInReport() bool {
	if o == nil || IsNil(o.IncludeInReport) {
		var ret bool
		return ret
	}
	return *o.IncludeInReport
}

// GetIncludeInReportOk returns a tuple with the IncludeInReport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatBase) GetIncludeInReportOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeInReport) {
		return nil, false
	}
	return o.IncludeInReport, true
}

// HasIncludeInReport returns a boolean if a field has been set.
func (o *ThreatBase) HasIncludeInReport() bool {
	if o != nil && !IsNil(o.IncludeInReport) {
		return true
	}

	return false
}

// SetIncludeInReport gets a reference to the given bool and assigns it to the IncludeInReport field.
func (o *ThreatBase) SetIncludeInReport(v bool) {
	o.IncludeInReport = &v
}

func (o ThreatBase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThreatBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Mitigation) {
		toSerialize["mitigation"] = o.Mitigation
	}
	if o.DiagramId.IsSet() {
		toSerialize["diagram_id"] = o.DiagramId.Get()
	}
	if o.CellId.IsSet() {
		toSerialize["cell_id"] = o.CellId.Get()
	}
	if !IsNil(o.Severity) {
		toSerialize["severity"] = o.Severity
	}
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.Mitigated) {
		toSerialize["mitigated"] = o.Mitigated
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["threat_type"] = o.ThreatType
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.IssueUri) {
		toSerialize["issue_uri"] = o.IssueUri
	}
	if o.AssetId.IsSet() {
		toSerialize["asset_id"] = o.AssetId.Get()
	}
	if !IsNil(o.CweId) {
		toSerialize["cwe_id"] = o.CweId
	}
	if !IsNil(o.Cvss) {
		toSerialize["cvss"] = o.Cvss
	}
	if !IsNil(o.IncludeInReport) {
		toSerialize["include_in_report"] = o.IncludeInReport
	}
	return toSerialize, nil
}

func (o *ThreatBase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"threat_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varThreatBase := _ThreatBase{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varThreatBase)

	if err != nil {
		return err
	}

	*o = ThreatBase(varThreatBase)

	return err
}

type NullableThreatBase struct {
	value *ThreatBase
	isSet bool
}

func (v NullableThreatBase) Get() *ThreatBase {
	return v.value
}

func (v *NullableThreatBase) Set(val *ThreatBase) {
	v.value = val
	v.isSet = true
}

func (v NullableThreatBase) IsSet() bool {
	return v.isSet
}

func (v *NullableThreatBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThreatBase(val *ThreatBase) *NullableThreatBase {
	return &NullableThreatBase{value: val, isSet: true}
}

func (v NullableThreatBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThreatBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


