/* tslint:disable */
/* eslint-disable */
/**
 * TMI (Threat Modeling Improved) API
 * A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: eric@tmi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EmbeddingProviderConfig
 */
export interface EmbeddingProviderConfig {
  /**
   * Embedding provider name
   * @type {string}
   * @memberof EmbeddingProviderConfig
   */
  provider: string;
  /**
   * Embedding model name
   * @type {string}
   * @memberof EmbeddingProviderConfig
   */
  model: string;
  /**
   * Embedding provider API key
   * @type {string}
   * @memberof EmbeddingProviderConfig
   */
  api_key?: string;
  /**
   * Custom base URL for self-hosted endpoints
   * @type {string}
   * @memberof EmbeddingProviderConfig
   */
  base_url?: string;
}

/**
 * Check if a given object implements the EmbeddingProviderConfig interface.
 */
export function instanceOfEmbeddingProviderConfig(
  value: object,
): value is EmbeddingProviderConfig {
  if (!("provider" in value) || value["provider"] === undefined) return false;
  if (!("model" in value) || value["model"] === undefined) return false;
  return true;
}

export function EmbeddingProviderConfigFromJSON(
  json: any,
): EmbeddingProviderConfig {
  return EmbeddingProviderConfigFromJSONTyped(json, false);
}

export function EmbeddingProviderConfigFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EmbeddingProviderConfig {
  if (json == null) {
    return json;
  }
  return {
    provider: json["provider"],
    model: json["model"],
    api_key: json["api_key"] == null ? undefined : json["api_key"],
    base_url: json["base_url"] == null ? undefined : json["base_url"],
  };
}

export function EmbeddingProviderConfigToJSON(
  json: any,
): EmbeddingProviderConfig {
  return EmbeddingProviderConfigToJSONTyped(json, false);
}

export function EmbeddingProviderConfigToJSONTyped(
  value?: EmbeddingProviderConfig | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    provider: value["provider"],
    model: value["model"],
    api_key: value["api_key"],
    base_url: value["base_url"],
  };
}
