/* tslint:disable */
/* eslint-disable */
/**
 * TMI (Threat Modeling Improved) API
 * A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: eric@tmi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TeamNoteListItem } from "./TeamNoteListItem";
import {
  TeamNoteListItemFromJSON,
  TeamNoteListItemFromJSONTyped,
  TeamNoteListItemToJSON,
  TeamNoteListItemToJSONTyped,
} from "./TeamNoteListItem";

/**
 * Paginated list of team notes
 * @export
 * @interface ListTeamNotesResponse
 */
export interface ListTeamNotesResponse {
  /**
   *
   * @type {Array<TeamNoteListItem>}
   * @memberof ListTeamNotesResponse
   */
  notes: Array<TeamNoteListItem>;
  /**
   * Total number of team notes matching criteria
   * @type {number}
   * @memberof ListTeamNotesResponse
   */
  total: number;
  /**
   * Pagination limit
   * @type {number}
   * @memberof ListTeamNotesResponse
   */
  limit: number;
  /**
   * Pagination offset
   * @type {number}
   * @memberof ListTeamNotesResponse
   */
  offset: number;
}

/**
 * Check if a given object implements the ListTeamNotesResponse interface.
 */
export function instanceOfListTeamNotesResponse(
  value: object,
): value is ListTeamNotesResponse {
  if (!("notes" in value) || value["notes"] === undefined) return false;
  if (!("total" in value) || value["total"] === undefined) return false;
  if (!("limit" in value) || value["limit"] === undefined) return false;
  if (!("offset" in value) || value["offset"] === undefined) return false;
  return true;
}

export function ListTeamNotesResponseFromJSON(
  json: any,
): ListTeamNotesResponse {
  return ListTeamNotesResponseFromJSONTyped(json, false);
}

export function ListTeamNotesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListTeamNotesResponse {
  if (json == null) {
    return json;
  }
  return {
    notes: (json["notes"] as Array<any>).map(TeamNoteListItemFromJSON),
    total: json["total"],
    limit: json["limit"],
    offset: json["offset"],
  };
}

export function ListTeamNotesResponseToJSON(json: any): ListTeamNotesResponse {
  return ListTeamNotesResponseToJSONTyped(json, false);
}

export function ListTeamNotesResponseToJSONTyped(
  value?: ListTeamNotesResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    notes: (value["notes"] as Array<any>).map(TeamNoteListItemToJSON),
    total: value["total"],
    limit: value["limit"],
    offset: value["offset"],
  };
}
