/*
TMI (Threat Modeling Improved) API

A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement 

API version: 1.4.0
Contact: api@tmi.local.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmiclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DeletionChallenge type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeletionChallenge{}

// DeletionChallenge Challenge response for user account deletion
type DeletionChallenge struct {
	// The exact challenge string that must be provided to confirm deletion
	ChallengeText string `json:"challenge_text" validate:"regexp=^[^\\\\x00-\\\\x1F]*$"`
	// When the challenge expires (3 minutes from issuance)
	ExpiresAt time.Time `json:"expires_at" validate:"regexp=^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\\\.[0-9]{1,6})?(Z|[+-][0-9]{2}:[0-9]{2})$"`
}

type _DeletionChallenge DeletionChallenge

// NewDeletionChallenge instantiates a new DeletionChallenge object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletionChallenge(challengeText string, expiresAt time.Time) *DeletionChallenge {
	this := DeletionChallenge{}
	this.ChallengeText = challengeText
	this.ExpiresAt = expiresAt
	return &this
}

// NewDeletionChallengeWithDefaults instantiates a new DeletionChallenge object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletionChallengeWithDefaults() *DeletionChallenge {
	this := DeletionChallenge{}
	return &this
}

// GetChallengeText returns the ChallengeText field value
func (o *DeletionChallenge) GetChallengeText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChallengeText
}

// GetChallengeTextOk returns a tuple with the ChallengeText field value
// and a boolean to check if the value has been set.
func (o *DeletionChallenge) GetChallengeTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChallengeText, true
}

// SetChallengeText sets field value
func (o *DeletionChallenge) SetChallengeText(v string) {
	o.ChallengeText = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *DeletionChallenge) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *DeletionChallenge) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *DeletionChallenge) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

func (o DeletionChallenge) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeletionChallenge) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["challenge_text"] = o.ChallengeText
	toSerialize["expires_at"] = o.ExpiresAt
	return toSerialize, nil
}

func (o *DeletionChallenge) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"challenge_text",
		"expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeletionChallenge := _DeletionChallenge{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeletionChallenge)

	if err != nil {
		return err
	}

	*o = DeletionChallenge(varDeletionChallenge)

	return err
}

type NullableDeletionChallenge struct {
	value *DeletionChallenge
	isSet bool
}

func (v NullableDeletionChallenge) Get() *DeletionChallenge {
	return v.value
}

func (v *NullableDeletionChallenge) Set(val *DeletionChallenge) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletionChallenge) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletionChallenge) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletionChallenge(val *DeletionChallenge) *NullableDeletionChallenge {
	return &NullableDeletionChallenge{value: val, isSet: true}
}

func (v NullableDeletionChallenge) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletionChallenge) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


