/* tslint:disable */
/* eslint-disable */
/**
 * TMI (Threat Modeling Improved) API
 * A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: api@tmi.local.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddonInvocationQuota } from './AddonInvocationQuota';
import {
    AddonInvocationQuotaFromJSON,
    AddonInvocationQuotaFromJSONTyped,
    AddonInvocationQuotaToJSON,
    AddonInvocationQuotaToJSONTyped,
} from './AddonInvocationQuota';

/**
 * Paginated list of addon quotas
 * @export
 * @interface ListAddonQuotasResponse
 */
export interface ListAddonQuotasResponse {
    /**
     * 
     * @type {Array<AddonInvocationQuota>}
     * @memberof ListAddonQuotasResponse
     */
    quotas: Array<AddonInvocationQuota>;
    /**
     * Total number of quotas matching criteria
     * @type {number}
     * @memberof ListAddonQuotasResponse
     */
    total: number;
    /**
     * Pagination limit
     * @type {number}
     * @memberof ListAddonQuotasResponse
     */
    limit: number;
    /**
     * Pagination offset
     * @type {number}
     * @memberof ListAddonQuotasResponse
     */
    offset: number;
}

/**
 * Check if a given object implements the ListAddonQuotasResponse interface.
 */
export function instanceOfListAddonQuotasResponse(value: object): value is ListAddonQuotasResponse {
    if (!('quotas' in value) || value['quotas'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function ListAddonQuotasResponseFromJSON(json: any): ListAddonQuotasResponse {
    return ListAddonQuotasResponseFromJSONTyped(json, false);
}

export function ListAddonQuotasResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAddonQuotasResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'quotas': ((json['quotas'] as Array<any>).map(AddonInvocationQuotaFromJSON)),
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
    };
}

export function ListAddonQuotasResponseToJSON(json: any): ListAddonQuotasResponse {
    return ListAddonQuotasResponseToJSONTyped(json, false);
}

export function ListAddonQuotasResponseToJSONTyped(value?: ListAddonQuotasResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quotas': ((value['quotas'] as Array<any>).map(AddonInvocationQuotaToJSON)),
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

