/*
TMI (Threat Modeling Improved) API

A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement 

API version: 1.4.0
Contact: api@tmi.local.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmiclient

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// NodeAttrsTextRefX - Horizontal position (0-1 relative, pixels, or percentage string e.g. '50%')
type NodeAttrsTextRefX struct {
	Float32 *float32
	String *string
}

// float32AsNodeAttrsTextRefX is a convenience function that returns float32 wrapped in NodeAttrsTextRefX
func Float32AsNodeAttrsTextRefX(v *float32) NodeAttrsTextRefX {
	return NodeAttrsTextRefX{
		Float32: v,
	}
}

// stringAsNodeAttrsTextRefX is a convenience function that returns string wrapped in NodeAttrsTextRefX
func StringAsNodeAttrsTextRefX(v *string) NodeAttrsTextRefX {
	return NodeAttrsTextRefX{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *NodeAttrsTextRefX) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Float32
	err = newStrictDecoder(data).Decode(&dst.Float32)
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			if err = validator.Validate(dst.Float32); err != nil {
				dst.Float32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Float32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(NodeAttrsTextRefX)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(NodeAttrsTextRefX)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src NodeAttrsTextRefX) MarshalJSON() ([]byte, error) {
	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *NodeAttrsTextRefX) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Float32 != nil {
		return obj.Float32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj NodeAttrsTextRefX) GetActualInstanceValue() (interface{}) {
	if obj.Float32 != nil {
		return *obj.Float32
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableNodeAttrsTextRefX struct {
	value *NodeAttrsTextRefX
	isSet bool
}

func (v NullableNodeAttrsTextRefX) Get() *NodeAttrsTextRefX {
	return v.value
}

func (v *NullableNodeAttrsTextRefX) Set(val *NodeAttrsTextRefX) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeAttrsTextRefX) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeAttrsTextRefX) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeAttrsTextRefX(val *NodeAttrsTextRefX) *NullableNodeAttrsTextRefX {
	return &NullableNodeAttrsTextRefX{value: val, isSet: true}
}

func (v NullableNodeAttrsTextRefX) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeAttrsTextRefX) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


