/*
TMI (Threat Modeling Improved) API

A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement 

API version: 1.4.0
Contact: api@tmi.local.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmbeddingIngestionItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmbeddingIngestionItem{}

// EmbeddingIngestionItem struct for EmbeddingIngestionItem
type EmbeddingIngestionItem struct {
	// Entity type (e.g., repository, asset)
	EntityType string `json:"entity_type"`
	// Entity UUID
	EntityId string `json:"entity_id"`
	// Sequential chunk number
	ChunkIndex int32 `json:"chunk_index"`
	// Original text of the chunk
	ChunkText string `json:"chunk_text"`
	// SHA256 hash of the original content
	ContentHash string `json:"content_hash"`
	// Model used to generate the embedding
	EmbeddingModel string `json:"embedding_model"`
	// Embedding vector dimension
	EmbeddingDim int32 `json:"embedding_dim"`
	// Embedding vector
	Vector []float32 `json:"vector"`
}

type _EmbeddingIngestionItem EmbeddingIngestionItem

// NewEmbeddingIngestionItem instantiates a new EmbeddingIngestionItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmbeddingIngestionItem(entityType string, entityId string, chunkIndex int32, chunkText string, contentHash string, embeddingModel string, embeddingDim int32, vector []float32) *EmbeddingIngestionItem {
	this := EmbeddingIngestionItem{}
	this.EntityType = entityType
	this.EntityId = entityId
	this.ChunkIndex = chunkIndex
	this.ChunkText = chunkText
	this.ContentHash = contentHash
	this.EmbeddingModel = embeddingModel
	this.EmbeddingDim = embeddingDim
	this.Vector = vector
	return &this
}

// NewEmbeddingIngestionItemWithDefaults instantiates a new EmbeddingIngestionItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmbeddingIngestionItemWithDefaults() *EmbeddingIngestionItem {
	this := EmbeddingIngestionItem{}
	return &this
}

// GetEntityType returns the EntityType field value
func (o *EmbeddingIngestionItem) GetEntityType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntityType
}

// GetEntityTypeOk returns a tuple with the EntityType field value
// and a boolean to check if the value has been set.
func (o *EmbeddingIngestionItem) GetEntityTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityType, true
}

// SetEntityType sets field value
func (o *EmbeddingIngestionItem) SetEntityType(v string) {
	o.EntityType = v
}

// GetEntityId returns the EntityId field value
func (o *EmbeddingIngestionItem) GetEntityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntityId
}

// GetEntityIdOk returns a tuple with the EntityId field value
// and a boolean to check if the value has been set.
func (o *EmbeddingIngestionItem) GetEntityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityId, true
}

// SetEntityId sets field value
func (o *EmbeddingIngestionItem) SetEntityId(v string) {
	o.EntityId = v
}

// GetChunkIndex returns the ChunkIndex field value
func (o *EmbeddingIngestionItem) GetChunkIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChunkIndex
}

// GetChunkIndexOk returns a tuple with the ChunkIndex field value
// and a boolean to check if the value has been set.
func (o *EmbeddingIngestionItem) GetChunkIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChunkIndex, true
}

// SetChunkIndex sets field value
func (o *EmbeddingIngestionItem) SetChunkIndex(v int32) {
	o.ChunkIndex = v
}

// GetChunkText returns the ChunkText field value
func (o *EmbeddingIngestionItem) GetChunkText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChunkText
}

// GetChunkTextOk returns a tuple with the ChunkText field value
// and a boolean to check if the value has been set.
func (o *EmbeddingIngestionItem) GetChunkTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChunkText, true
}

// SetChunkText sets field value
func (o *EmbeddingIngestionItem) SetChunkText(v string) {
	o.ChunkText = v
}

// GetContentHash returns the ContentHash field value
func (o *EmbeddingIngestionItem) GetContentHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentHash
}

// GetContentHashOk returns a tuple with the ContentHash field value
// and a boolean to check if the value has been set.
func (o *EmbeddingIngestionItem) GetContentHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentHash, true
}

// SetContentHash sets field value
func (o *EmbeddingIngestionItem) SetContentHash(v string) {
	o.ContentHash = v
}

// GetEmbeddingModel returns the EmbeddingModel field value
func (o *EmbeddingIngestionItem) GetEmbeddingModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmbeddingModel
}

// GetEmbeddingModelOk returns a tuple with the EmbeddingModel field value
// and a boolean to check if the value has been set.
func (o *EmbeddingIngestionItem) GetEmbeddingModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmbeddingModel, true
}

// SetEmbeddingModel sets field value
func (o *EmbeddingIngestionItem) SetEmbeddingModel(v string) {
	o.EmbeddingModel = v
}

// GetEmbeddingDim returns the EmbeddingDim field value
func (o *EmbeddingIngestionItem) GetEmbeddingDim() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EmbeddingDim
}

// GetEmbeddingDimOk returns a tuple with the EmbeddingDim field value
// and a boolean to check if the value has been set.
func (o *EmbeddingIngestionItem) GetEmbeddingDimOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmbeddingDim, true
}

// SetEmbeddingDim sets field value
func (o *EmbeddingIngestionItem) SetEmbeddingDim(v int32) {
	o.EmbeddingDim = v
}

// GetVector returns the Vector field value
func (o *EmbeddingIngestionItem) GetVector() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}

	return o.Vector
}

// GetVectorOk returns a tuple with the Vector field value
// and a boolean to check if the value has been set.
func (o *EmbeddingIngestionItem) GetVectorOk() ([]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vector, true
}

// SetVector sets field value
func (o *EmbeddingIngestionItem) SetVector(v []float32) {
	o.Vector = v
}

func (o EmbeddingIngestionItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmbeddingIngestionItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entity_type"] = o.EntityType
	toSerialize["entity_id"] = o.EntityId
	toSerialize["chunk_index"] = o.ChunkIndex
	toSerialize["chunk_text"] = o.ChunkText
	toSerialize["content_hash"] = o.ContentHash
	toSerialize["embedding_model"] = o.EmbeddingModel
	toSerialize["embedding_dim"] = o.EmbeddingDim
	toSerialize["vector"] = o.Vector
	return toSerialize, nil
}

func (o *EmbeddingIngestionItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entity_type",
		"entity_id",
		"chunk_index",
		"chunk_text",
		"content_hash",
		"embedding_model",
		"embedding_dim",
		"vector",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmbeddingIngestionItem := _EmbeddingIngestionItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmbeddingIngestionItem)

	if err != nil {
		return err
	}

	*o = EmbeddingIngestionItem(varEmbeddingIngestionItem)

	return err
}

type NullableEmbeddingIngestionItem struct {
	value *EmbeddingIngestionItem
	isSet bool
}

func (v NullableEmbeddingIngestionItem) Get() *EmbeddingIngestionItem {
	return v.value
}

func (v *NullableEmbeddingIngestionItem) Set(val *EmbeddingIngestionItem) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbeddingIngestionItem) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbeddingIngestionItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbeddingIngestionItem(val *EmbeddingIngestionItem) *NullableEmbeddingIngestionItem {
	return &NullableEmbeddingIngestionItem{value: val, isSet: true}
}

func (v NullableEmbeddingIngestionItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbeddingIngestionItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


