/* tslint:disable */
/* eslint-disable */
/**
 * TMI (Threat Modeling Improved) API
 * A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement 
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: api@tmi.local.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserAPIQuota429Response
 */
export interface GetUserAPIQuota429Response {
    /**
     * Error message
     * @type {string}
     * @memberof GetUserAPIQuota429Response
     */
    error: string;
    /**
     * Seconds until rate limit resets
     * @type {number}
     * @memberof GetUserAPIQuota429Response
     */
    retry_after?: number;
}

/**
 * Check if a given object implements the GetUserAPIQuota429Response interface.
 */
export function instanceOfGetUserAPIQuota429Response(value: object): value is GetUserAPIQuota429Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function GetUserAPIQuota429ResponseFromJSON(json: any): GetUserAPIQuota429Response {
    return GetUserAPIQuota429ResponseFromJSONTyped(json, false);
}

export function GetUserAPIQuota429ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserAPIQuota429Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'retry_after': json['retry_after'] == null ? undefined : json['retry_after'],
    };
}

export function GetUserAPIQuota429ResponseToJSON(json: any): GetUserAPIQuota429Response {
    return GetUserAPIQuota429ResponseToJSONTyped(json, false);
}

export function GetUserAPIQuota429ResponseToJSONTyped(value?: GetUserAPIQuota429Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'retry_after': value['retry_after'],
    };
}

