/* tslint:disable */
/* eslint-disable */
/**
 * TMI (Threat Modeling Improved) API
 * A RESTful API for collaborative threat modeling with full X6 graph library compatibility. This API provides schemas that align with AntV X6 cell object models for seamless integration with modern diagramming libraries. Supports OAuth 2.0 authentication with client callback integration for seamless single-page application authentication flows.  ## API Design v1.1.0  ### Authorization Model TMI uses hierarchical authorization: access control is defined at the ThreatModel level via the authorization field (readers, writers, owners). All child resources (Assets, Diagrams, Documents, Notes, Repositories, Threats) inherit permissions from their parent ThreatModel. This simplifies permission management and ensures consistent access control.  ### Bulk Operations Notes and Diagrams do not support bulk operations due to their unique creation workflows and lack of valid bulk use cases. All other resources (Threats, Assets, Documents, Repositories) support full bulk operations: POST (create), PUT (upsert), PATCH (partial update), DELETE (batch delete).  All resources support bulk metadata operations regardless of resource-level bulk support.  ### List Response Strategy - ThreatModels return summary information (TMListItem) because they contain many child objects that can be large. - Diagrams return summary information (DiagramListItem) because diagram data (cells, images) can be large. - Notes return summary information (NoteListItem) because the content field can be large. - Threats, Assets, Documents, Repositories return full schemas as they are relatively small and static.  ### PATCH Support All resources support PATCH for partial updates using JSON Patch (RFC 6902). This is particularly useful for: - Assets: Array field updates (affected_assets, trust_boundaries) ensuring no duplicates - Notes: Updating name/description without changing content field - All resources: Efficient updates without full object replacement 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: api@tmi.local.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BulkPatchRequest,
  JsonPatchDocumentInner,
  ListTeamNotesResponse,
  ListTeamsResponse,
  Metadata,
  RelationshipType,
  Team,
  TeamBase,
  TeamNote,
  TeamProjectNoteBase,
} from '../models/index';
import {
    BulkPatchRequestFromJSON,
    BulkPatchRequestToJSON,
    JsonPatchDocumentInnerFromJSON,
    JsonPatchDocumentInnerToJSON,
    ListTeamNotesResponseFromJSON,
    ListTeamNotesResponseToJSON,
    ListTeamsResponseFromJSON,
    ListTeamsResponseToJSON,
    MetadataFromJSON,
    MetadataToJSON,
    RelationshipTypeFromJSON,
    RelationshipTypeToJSON,
    TeamFromJSON,
    TeamToJSON,
    TeamBaseFromJSON,
    TeamBaseToJSON,
    TeamNoteFromJSON,
    TeamNoteToJSON,
    TeamProjectNoteBaseFromJSON,
    TeamProjectNoteBaseToJSON,
} from '../models/index';

export interface BulkCreateTeamMetadataRequest {
    teamId: string;
    metadata: Array<Metadata>;
}

export interface BulkReplaceTeamMetadataRequest {
    teamId: string;
    metadata: Array<Metadata>;
}

export interface BulkUpsertTeamMetadataRequest {
    teamId: string;
    bulkPatchRequest: BulkPatchRequest;
}

export interface CreateTeamRequest {
    body: TeamBase;
}

export interface CreateTeamMetadataRequest {
    teamId: string;
    metadata: Metadata;
}

export interface CreateTeamNoteRequest {
    teamId: string;
    body: TeamProjectNoteBase;
}

export interface DeleteTeamRequest {
    teamId: string;
}

export interface DeleteTeamMetadataRequest {
    teamId: string;
    key: string;
}

export interface DeleteTeamNoteRequest {
    teamId: string;
    teamNoteId: string;
}

export interface GetTeamRequest {
    teamId: string;
}

export interface GetTeamMetadataRequest {
    teamId: string;
}

export interface GetTeamNoteRequest {
    teamId: string;
    teamNoteId: string;
}

export interface ListTeamNotesRequest {
    teamId: string;
    limit?: number;
    offset?: number;
}

export interface ListTeamsRequest {
    limit?: number;
    offset?: number;
    name?: string;
    status?: string;
    memberUserId?: string;
    relatedTo?: string;
    relationship?: RelationshipType;
    transitive?: boolean;
}

export interface PatchTeamRequest {
    teamId: string;
    jsonPatchDocumentInner: Array<JsonPatchDocumentInner>;
}

export interface PatchTeamNoteRequest {
    teamId: string;
    teamNoteId: string;
    jsonPatchDocumentInner: Array<JsonPatchDocumentInner>;
}

export interface UpdateTeamRequest {
    teamId: string;
    body: TeamBase;
}

export interface UpdateTeamMetadataRequest {
    teamId: string;
    key: string;
    metadata: Metadata;
}

export interface UpdateTeamNoteRequest {
    teamId: string;
    teamNoteId: string;
    body: TeamProjectNoteBase;
}

/**
 * TeamsApi - interface
 * 
 * @export
 * @interface TeamsApiInterface
 */
export interface TeamsApiInterface {
    /**
     * Creates request options for bulkCreateTeamMetadata without sending the request
     * @param {string} teamId Team identifier (UUID)
     * @param {Array<Metadata>} metadata Bulk metadata entries to create
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    bulkCreateTeamMetadataRequestOpts(requestParameters: BulkCreateTeamMetadataRequest): Promise<runtime.RequestOpts>;

    /**
     * Create multiple metadata key-value pairs for the specified team in a single request.
     * @summary Bulk create team metadata
     * @param {string} teamId Team identifier (UUID)
     * @param {Array<Metadata>} metadata Bulk metadata entries to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    bulkCreateTeamMetadataRaw(requestParameters: BulkCreateTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Metadata>>>;

    /**
     * Create multiple metadata key-value pairs for the specified team in a single request.
     * Bulk create team metadata
     */
    bulkCreateTeamMetadata(requestParameters: BulkCreateTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Metadata>>;

    /**
     * Creates request options for bulkReplaceTeamMetadata without sending the request
     * @param {string} teamId Team identifier (UUID)
     * @param {Array<Metadata>} metadata Complete set of metadata entries for replacement
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    bulkReplaceTeamMetadataRequestOpts(requestParameters: BulkReplaceTeamMetadataRequest): Promise<runtime.RequestOpts>;

    /**
     * Replace all metadata for the specified team with the provided key-value pairs.
     * @summary Bulk replace team metadata
     * @param {string} teamId Team identifier (UUID)
     * @param {Array<Metadata>} metadata Complete set of metadata entries for replacement
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    bulkReplaceTeamMetadataRaw(requestParameters: BulkReplaceTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Metadata>>>;

    /**
     * Replace all metadata for the specified team with the provided key-value pairs.
     * Bulk replace team metadata
     */
    bulkReplaceTeamMetadata(requestParameters: BulkReplaceTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Metadata>>;

    /**
     * Creates request options for bulkUpsertTeamMetadata without sending the request
     * @param {string} teamId Team identifier (UUID)
     * @param {BulkPatchRequest} bulkPatchRequest Metadata entries to update
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    bulkUpsertTeamMetadataRequestOpts(requestParameters: BulkUpsertTeamMetadataRequest): Promise<runtime.RequestOpts>;

    /**
     * Create or update multiple metadata key-value pairs for the specified team in a single request.
     * @summary Bulk upsert team metadata
     * @param {string} teamId Team identifier (UUID)
     * @param {BulkPatchRequest} bulkPatchRequest Metadata entries to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    bulkUpsertTeamMetadataRaw(requestParameters: BulkUpsertTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Metadata>>>;

    /**
     * Create or update multiple metadata key-value pairs for the specified team in a single request.
     * Bulk upsert team metadata
     */
    bulkUpsertTeamMetadata(requestParameters: BulkUpsertTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Metadata>>;

    /**
     * Creates request options for createTeam without sending the request
     * @param {TeamBase} body Team creation data
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    createTeamRequestOpts(requestParameters: CreateTeamRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a new team. The creating user is automatically added as a member.
     * @summary Create a team
     * @param {TeamBase} body Team creation data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    createTeamRaw(requestParameters: CreateTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Team>>;

    /**
     * Creates a new team. The creating user is automatically added as a member.
     * Create a team
     */
    createTeam(requestParameters: CreateTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Team>;

    /**
     * Creates request options for createTeamMetadata without sending the request
     * @param {string} teamId Team identifier (UUID)
     * @param {Metadata} metadata Metadata entry to create
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    createTeamMetadataRequestOpts(requestParameters: CreateTeamMetadataRequest): Promise<runtime.RequestOpts>;

    /**
     * Create a new metadata key-value pair for the specified team.
     * @summary Create team metadata
     * @param {string} teamId Team identifier (UUID)
     * @param {Metadata} metadata Metadata entry to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    createTeamMetadataRaw(requestParameters: CreateTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Metadata>>;

    /**
     * Create a new metadata key-value pair for the specified team.
     * Create team metadata
     */
    createTeamMetadata(requestParameters: CreateTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Metadata>;

    /**
     * Creates request options for createTeamNote without sending the request
     * @param {string} teamId Team UUID
     * @param {TeamProjectNoteBase} body Team note creation data
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    createTeamNoteRequestOpts(requestParameters: CreateTeamNoteRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a new note within the specified team
     * @summary Create a new team note
     * @param {string} teamId Team UUID
     * @param {TeamProjectNoteBase} body Team note creation data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    createTeamNoteRaw(requestParameters: CreateTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamNote>>;

    /**
     * Creates a new note within the specified team
     * Create a new team note
     */
    createTeamNote(requestParameters: CreateTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamNote>;

    /**
     * Creates request options for deleteTeam without sending the request
     * @param {string} teamId Team UUID
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    deleteTeamRequestOpts(requestParameters: DeleteTeamRequest): Promise<runtime.RequestOpts>;

    /**
     * Deletes a team. Requires owner role or admin access. Returns 409 if the team is referenced by projects.
     * @summary Delete a team
     * @param {string} teamId Team UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    deleteTeamRaw(requestParameters: DeleteTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Deletes a team. Requires owner role or admin access. Returns 409 if the team is referenced by projects.
     * Delete a team
     */
    deleteTeam(requestParameters: DeleteTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for deleteTeamMetadata without sending the request
     * @param {string} teamId Team identifier (UUID)
     * @param {string} key Metadata key
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    deleteTeamMetadataRequestOpts(requestParameters: DeleteTeamMetadataRequest): Promise<runtime.RequestOpts>;

    /**
     * Delete a metadata key-value pair from the specified team.
     * @summary Delete team metadata
     * @param {string} teamId Team identifier (UUID)
     * @param {string} key Metadata key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    deleteTeamMetadataRaw(requestParameters: DeleteTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete a metadata key-value pair from the specified team.
     * Delete team metadata
     */
    deleteTeamMetadata(requestParameters: DeleteTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for deleteTeamNote without sending the request
     * @param {string} teamId Team UUID
     * @param {string} teamNoteId Team note identifier
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    deleteTeamNoteRequestOpts(requestParameters: DeleteTeamNoteRequest): Promise<runtime.RequestOpts>;

    /**
     * Deletes a specific note from the team
     * @summary Delete a team note
     * @param {string} teamId Team UUID
     * @param {string} teamNoteId Team note identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    deleteTeamNoteRaw(requestParameters: DeleteTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Deletes a specific note from the team
     * Delete a team note
     */
    deleteTeamNote(requestParameters: DeleteTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for getTeam without sending the request
     * @param {string} teamId Team UUID
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    getTeamRequestOpts(requestParameters: GetTeamRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns a team by ID. Requires team membership or admin access.
     * @summary Get a team
     * @param {string} teamId Team UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    getTeamRaw(requestParameters: GetTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Team>>;

    /**
     * Returns a team by ID. Requires team membership or admin access.
     * Get a team
     */
    getTeam(requestParameters: GetTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Team>;

    /**
     * Creates request options for getTeamMetadata without sending the request
     * @param {string} teamId Team identifier (UUID)
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    getTeamMetadataRequestOpts(requestParameters: GetTeamMetadataRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieve all metadata key-value pairs associated with the specified team.
     * @summary Get team metadata
     * @param {string} teamId Team identifier (UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    getTeamMetadataRaw(requestParameters: GetTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Metadata>>>;

    /**
     * Retrieve all metadata key-value pairs associated with the specified team.
     * Get team metadata
     */
    getTeamMetadata(requestParameters: GetTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Metadata>>;

    /**
     * Creates request options for getTeamNote without sending the request
     * @param {string} teamId Team UUID
     * @param {string} teamNoteId Team note identifier
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    getTeamNoteRequestOpts(requestParameters: GetTeamNoteRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns details of a specific note within the team
     * @summary Get a specific team note
     * @param {string} teamId Team UUID
     * @param {string} teamNoteId Team note identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    getTeamNoteRaw(requestParameters: GetTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamNote>>;

    /**
     * Returns details of a specific note within the team
     * Get a specific team note
     */
    getTeamNote(requestParameters: GetTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamNote>;

    /**
     * Creates request options for listTeamNotes without sending the request
     * @param {string} teamId Team UUID
     * @param {number} [limit] Maximum number of results to return
     * @param {number} [offset] Number of results to skip
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    listTeamNotesRequestOpts(requestParameters: ListTeamNotesRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns a paginated list of notes within the specified team
     * @summary List notes in a team
     * @param {string} teamId Team UUID
     * @param {number} [limit] Maximum number of results to return
     * @param {number} [offset] Number of results to skip
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    listTeamNotesRaw(requestParameters: ListTeamNotesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTeamNotesResponse>>;

    /**
     * Returns a paginated list of notes within the specified team
     * List notes in a team
     */
    listTeamNotes(requestParameters: ListTeamNotesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTeamNotesResponse>;

    /**
     * Creates request options for listTeams without sending the request
     * @param {number} [limit] Maximum number of results per page
     * @param {number} [offset] Number of results to skip
     * @param {string} [name] Filter by team name (partial match)
     * @param {string} [status] Filter by team lifecycle status (exact match, comma-separated for multiple). Valid values: active, on_hold, winding_down, archived, forming, merging, splitting
     * @param {string} [memberUserId] Filter teams that include this user as a member
     * @param {string} [relatedTo] Include teams related to this team ID
     * @param {RelationshipType} [relationship] Filter related teams by relationship type. Only used with related_to.
     * @param {boolean} [transitive] When true with related_to + relationship, follow parent/child chains transitively (max depth 10)
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    listTeamsRequestOpts(requestParameters: ListTeamsRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns a paginated list of teams. Non-admin users see only teams they are members of.
     * @summary List teams
     * @param {number} [limit] Maximum number of results per page
     * @param {number} [offset] Number of results to skip
     * @param {string} [name] Filter by team name (partial match)
     * @param {string} [status] Filter by team lifecycle status (exact match, comma-separated for multiple). Valid values: active, on_hold, winding_down, archived, forming, merging, splitting
     * @param {string} [memberUserId] Filter teams that include this user as a member
     * @param {string} [relatedTo] Include teams related to this team ID
     * @param {RelationshipType} [relationship] Filter related teams by relationship type. Only used with related_to.
     * @param {boolean} [transitive] When true with related_to + relationship, follow parent/child chains transitively (max depth 10)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    listTeamsRaw(requestParameters: ListTeamsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTeamsResponse>>;

    /**
     * Returns a paginated list of teams. Non-admin users see only teams they are members of.
     * List teams
     */
    listTeams(requestParameters: ListTeamsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTeamsResponse>;

    /**
     * Creates request options for patchTeam without sending the request
     * @param {string} teamId Team UUID
     * @param {Array<JsonPatchDocumentInner>} jsonPatchDocumentInner Partial team data for update
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    patchTeamRequestOpts(requestParameters: PatchTeamRequest): Promise<runtime.RequestOpts>;

    /**
     * Partial update of a team using JSON Patch (RFC 6902). Requires team membership or admin access.
     * @summary Patch a team
     * @param {string} teamId Team UUID
     * @param {Array<JsonPatchDocumentInner>} jsonPatchDocumentInner Partial team data for update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    patchTeamRaw(requestParameters: PatchTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Team>>;

    /**
     * Partial update of a team using JSON Patch (RFC 6902). Requires team membership or admin access.
     * Patch a team
     */
    patchTeam(requestParameters: PatchTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Team>;

    /**
     * Creates request options for patchTeamNote without sending the request
     * @param {string} teamId Team UUID
     * @param {string} teamNoteId Team note identifier
     * @param {Array<JsonPatchDocumentInner>} jsonPatchDocumentInner JSON Patch operations to apply to the team note
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    patchTeamNoteRequestOpts(requestParameters: PatchTeamNoteRequest): Promise<runtime.RequestOpts>;

    /**
     * Apply JSON Patch operations to partially update a team note
     * @summary Partially update a team note
     * @param {string} teamId Team UUID
     * @param {string} teamNoteId Team note identifier
     * @param {Array<JsonPatchDocumentInner>} jsonPatchDocumentInner JSON Patch operations to apply to the team note
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    patchTeamNoteRaw(requestParameters: PatchTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamNote>>;

    /**
     * Apply JSON Patch operations to partially update a team note
     * Partially update a team note
     */
    patchTeamNote(requestParameters: PatchTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamNote>;

    /**
     * Creates request options for updateTeam without sending the request
     * @param {string} teamId Team UUID
     * @param {TeamBase} body Complete team data for replacement
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    updateTeamRequestOpts(requestParameters: UpdateTeamRequest): Promise<runtime.RequestOpts>;

    /**
     * Full replacement update of a team. Requires team membership or admin access.
     * @summary Update a team
     * @param {string} teamId Team UUID
     * @param {TeamBase} body Complete team data for replacement
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    updateTeamRaw(requestParameters: UpdateTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Team>>;

    /**
     * Full replacement update of a team. Requires team membership or admin access.
     * Update a team
     */
    updateTeam(requestParameters: UpdateTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Team>;

    /**
     * Creates request options for updateTeamMetadata without sending the request
     * @param {string} teamId Team identifier (UUID)
     * @param {string} key Metadata key
     * @param {Metadata} metadata Metadata value to set for the specified key
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    updateTeamMetadataRequestOpts(requestParameters: UpdateTeamMetadataRequest): Promise<runtime.RequestOpts>;

    /**
     * Update the value of an existing metadata key for the specified team.
     * @summary Update team metadata
     * @param {string} teamId Team identifier (UUID)
     * @param {string} key Metadata key
     * @param {Metadata} metadata Metadata value to set for the specified key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    updateTeamMetadataRaw(requestParameters: UpdateTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Metadata>>;

    /**
     * Update the value of an existing metadata key for the specified team.
     * Update team metadata
     */
    updateTeamMetadata(requestParameters: UpdateTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Metadata>;

    /**
     * Creates request options for updateTeamNote without sending the request
     * @param {string} teamId Team UUID
     * @param {string} teamNoteId Team note identifier
     * @param {TeamProjectNoteBase} body Complete team note data for replacement
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    updateTeamNoteRequestOpts(requestParameters: UpdateTeamNoteRequest): Promise<runtime.RequestOpts>;

    /**
     * Updates a specific note within the team
     * @summary Update a team note
     * @param {string} teamId Team UUID
     * @param {string} teamNoteId Team note identifier
     * @param {TeamProjectNoteBase} body Complete team note data for replacement
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamsApiInterface
     */
    updateTeamNoteRaw(requestParameters: UpdateTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamNote>>;

    /**
     * Updates a specific note within the team
     * Update a team note
     */
    updateTeamNote(requestParameters: UpdateTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamNote>;

}

/**
 * 
 */
export class TeamsApi extends runtime.BaseAPI implements TeamsApiInterface {

    /**
     * Creates request options for bulkCreateTeamMetadata without sending the request
     */
    async bulkCreateTeamMetadataRequestOpts(requestParameters: BulkCreateTeamMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling bulkCreateTeamMetadata().'
            );
        }

        if (requestParameters['metadata'] == null) {
            throw new runtime.RequiredError(
                'metadata',
                'Required parameter "metadata" was null or undefined when calling bulkCreateTeamMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}/metadata/bulk`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['metadata']!.map(MetadataToJSON),
        };
    }

    /**
     * Create multiple metadata key-value pairs for the specified team in a single request.
     * Bulk create team metadata
     */
    async bulkCreateTeamMetadataRaw(requestParameters: BulkCreateTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Metadata>>> {
        const requestOptions = await this.bulkCreateTeamMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MetadataFromJSON));
    }

    /**
     * Create multiple metadata key-value pairs for the specified team in a single request.
     * Bulk create team metadata
     */
    async bulkCreateTeamMetadata(requestParameters: BulkCreateTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Metadata>> {
        const response = await this.bulkCreateTeamMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for bulkReplaceTeamMetadata without sending the request
     */
    async bulkReplaceTeamMetadataRequestOpts(requestParameters: BulkReplaceTeamMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling bulkReplaceTeamMetadata().'
            );
        }

        if (requestParameters['metadata'] == null) {
            throw new runtime.RequiredError(
                'metadata',
                'Required parameter "metadata" was null or undefined when calling bulkReplaceTeamMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}/metadata/bulk`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['metadata']!.map(MetadataToJSON),
        };
    }

    /**
     * Replace all metadata for the specified team with the provided key-value pairs.
     * Bulk replace team metadata
     */
    async bulkReplaceTeamMetadataRaw(requestParameters: BulkReplaceTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Metadata>>> {
        const requestOptions = await this.bulkReplaceTeamMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MetadataFromJSON));
    }

    /**
     * Replace all metadata for the specified team with the provided key-value pairs.
     * Bulk replace team metadata
     */
    async bulkReplaceTeamMetadata(requestParameters: BulkReplaceTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Metadata>> {
        const response = await this.bulkReplaceTeamMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for bulkUpsertTeamMetadata without sending the request
     */
    async bulkUpsertTeamMetadataRequestOpts(requestParameters: BulkUpsertTeamMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling bulkUpsertTeamMetadata().'
            );
        }

        if (requestParameters['bulkPatchRequest'] == null) {
            throw new runtime.RequiredError(
                'bulkPatchRequest',
                'Required parameter "bulkPatchRequest" was null or undefined when calling bulkUpsertTeamMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}/metadata/bulk`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: BulkPatchRequestToJSON(requestParameters['bulkPatchRequest']),
        };
    }

    /**
     * Create or update multiple metadata key-value pairs for the specified team in a single request.
     * Bulk upsert team metadata
     */
    async bulkUpsertTeamMetadataRaw(requestParameters: BulkUpsertTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Metadata>>> {
        const requestOptions = await this.bulkUpsertTeamMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MetadataFromJSON));
    }

    /**
     * Create or update multiple metadata key-value pairs for the specified team in a single request.
     * Bulk upsert team metadata
     */
    async bulkUpsertTeamMetadata(requestParameters: BulkUpsertTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Metadata>> {
        const response = await this.bulkUpsertTeamMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTeam without sending the request
     */
    async createTeamRequestOpts(requestParameters: CreateTeamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling createTeam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Creates a new team. The creating user is automatically added as a member.
     * Create a team
     */
    async createTeamRaw(requestParameters: CreateTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Team>> {
        const requestOptions = await this.createTeamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamFromJSON(jsonValue));
    }

    /**
     * Creates a new team. The creating user is automatically added as a member.
     * Create a team
     */
    async createTeam(requestParameters: CreateTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Team> {
        const response = await this.createTeamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTeamMetadata without sending the request
     */
    async createTeamMetadataRequestOpts(requestParameters: CreateTeamMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling createTeamMetadata().'
            );
        }

        if (requestParameters['metadata'] == null) {
            throw new runtime.RequiredError(
                'metadata',
                'Required parameter "metadata" was null or undefined when calling createTeamMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}/metadata`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MetadataToJSON(requestParameters['metadata']),
        };
    }

    /**
     * Create a new metadata key-value pair for the specified team.
     * Create team metadata
     */
    async createTeamMetadataRaw(requestParameters: CreateTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Metadata>> {
        const requestOptions = await this.createTeamMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataFromJSON(jsonValue));
    }

    /**
     * Create a new metadata key-value pair for the specified team.
     * Create team metadata
     */
    async createTeamMetadata(requestParameters: CreateTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Metadata> {
        const response = await this.createTeamMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTeamNote without sending the request
     */
    async createTeamNoteRequestOpts(requestParameters: CreateTeamNoteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling createTeamNote().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling createTeamNote().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}/notes`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Creates a new note within the specified team
     * Create a new team note
     */
    async createTeamNoteRaw(requestParameters: CreateTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamNote>> {
        const requestOptions = await this.createTeamNoteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamNoteFromJSON(jsonValue));
    }

    /**
     * Creates a new note within the specified team
     * Create a new team note
     */
    async createTeamNote(requestParameters: CreateTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamNote> {
        const response = await this.createTeamNoteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTeam without sending the request
     */
    async deleteTeamRequestOpts(requestParameters: DeleteTeamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling deleteTeam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes a team. Requires owner role or admin access. Returns 409 if the team is referenced by projects.
     * Delete a team
     */
    async deleteTeamRaw(requestParameters: DeleteTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTeamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a team. Requires owner role or admin access. Returns 409 if the team is referenced by projects.
     * Delete a team
     */
    async deleteTeam(requestParameters: DeleteTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTeamRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteTeamMetadata without sending the request
     */
    async deleteTeamMetadataRequestOpts(requestParameters: DeleteTeamMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling deleteTeamMetadata().'
            );
        }

        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling deleteTeamMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}/metadata/{key}`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));
        urlPath = urlPath.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a metadata key-value pair from the specified team.
     * Delete team metadata
     */
    async deleteTeamMetadataRaw(requestParameters: DeleteTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTeamMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a metadata key-value pair from the specified team.
     * Delete team metadata
     */
    async deleteTeamMetadata(requestParameters: DeleteTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTeamMetadataRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteTeamNote without sending the request
     */
    async deleteTeamNoteRequestOpts(requestParameters: DeleteTeamNoteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling deleteTeamNote().'
            );
        }

        if (requestParameters['teamNoteId'] == null) {
            throw new runtime.RequiredError(
                'teamNoteId',
                'Required parameter "teamNoteId" was null or undefined when calling deleteTeamNote().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}/notes/{team_note_id}`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));
        urlPath = urlPath.replace(`{${"team_note_id"}}`, encodeURIComponent(String(requestParameters['teamNoteId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes a specific note from the team
     * Delete a team note
     */
    async deleteTeamNoteRaw(requestParameters: DeleteTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTeamNoteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a specific note from the team
     * Delete a team note
     */
    async deleteTeamNote(requestParameters: DeleteTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTeamNoteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getTeam without sending the request
     */
    async getTeamRequestOpts(requestParameters: GetTeamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling getTeam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a team by ID. Requires team membership or admin access.
     * Get a team
     */
    async getTeamRaw(requestParameters: GetTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Team>> {
        const requestOptions = await this.getTeamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamFromJSON(jsonValue));
    }

    /**
     * Returns a team by ID. Requires team membership or admin access.
     * Get a team
     */
    async getTeam(requestParameters: GetTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Team> {
        const response = await this.getTeamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTeamMetadata without sending the request
     */
    async getTeamMetadataRequestOpts(requestParameters: GetTeamMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling getTeamMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}/metadata`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve all metadata key-value pairs associated with the specified team.
     * Get team metadata
     */
    async getTeamMetadataRaw(requestParameters: GetTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Metadata>>> {
        const requestOptions = await this.getTeamMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MetadataFromJSON));
    }

    /**
     * Retrieve all metadata key-value pairs associated with the specified team.
     * Get team metadata
     */
    async getTeamMetadata(requestParameters: GetTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Metadata>> {
        const response = await this.getTeamMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTeamNote without sending the request
     */
    async getTeamNoteRequestOpts(requestParameters: GetTeamNoteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling getTeamNote().'
            );
        }

        if (requestParameters['teamNoteId'] == null) {
            throw new runtime.RequiredError(
                'teamNoteId',
                'Required parameter "teamNoteId" was null or undefined when calling getTeamNote().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}/notes/{team_note_id}`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));
        urlPath = urlPath.replace(`{${"team_note_id"}}`, encodeURIComponent(String(requestParameters['teamNoteId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns details of a specific note within the team
     * Get a specific team note
     */
    async getTeamNoteRaw(requestParameters: GetTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamNote>> {
        const requestOptions = await this.getTeamNoteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamNoteFromJSON(jsonValue));
    }

    /**
     * Returns details of a specific note within the team
     * Get a specific team note
     */
    async getTeamNote(requestParameters: GetTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamNote> {
        const response = await this.getTeamNoteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTeamNotes without sending the request
     */
    async listTeamNotesRequestOpts(requestParameters: ListTeamNotesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling listTeamNotes().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}/notes`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a paginated list of notes within the specified team
     * List notes in a team
     */
    async listTeamNotesRaw(requestParameters: ListTeamNotesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTeamNotesResponse>> {
        const requestOptions = await this.listTeamNotesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTeamNotesResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of notes within the specified team
     * List notes in a team
     */
    async listTeamNotes(requestParameters: ListTeamNotesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTeamNotesResponse> {
        const response = await this.listTeamNotesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTeams without sending the request
     */
    async listTeamsRequestOpts(requestParameters: ListTeamsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['memberUserId'] != null) {
            queryParameters['member_user_id'] = requestParameters['memberUserId'];
        }

        if (requestParameters['relatedTo'] != null) {
            queryParameters['related_to'] = requestParameters['relatedTo'];
        }

        if (requestParameters['relationship'] != null) {
            queryParameters['relationship'] = requestParameters['relationship'];
        }

        if (requestParameters['transitive'] != null) {
            queryParameters['transitive'] = requestParameters['transitive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a paginated list of teams. Non-admin users see only teams they are members of.
     * List teams
     */
    async listTeamsRaw(requestParameters: ListTeamsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTeamsResponse>> {
        const requestOptions = await this.listTeamsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTeamsResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of teams. Non-admin users see only teams they are members of.
     * List teams
     */
    async listTeams(requestParameters: ListTeamsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTeamsResponse> {
        const response = await this.listTeamsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchTeam without sending the request
     */
    async patchTeamRequestOpts(requestParameters: PatchTeamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling patchTeam().'
            );
        }

        if (requestParameters['jsonPatchDocumentInner'] == null) {
            throw new runtime.RequiredError(
                'jsonPatchDocumentInner',
                'Required parameter "jsonPatchDocumentInner" was null or undefined when calling patchTeam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['jsonPatchDocumentInner']!.map(JsonPatchDocumentInnerToJSON),
        };
    }

    /**
     * Partial update of a team using JSON Patch (RFC 6902). Requires team membership or admin access.
     * Patch a team
     */
    async patchTeamRaw(requestParameters: PatchTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Team>> {
        const requestOptions = await this.patchTeamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamFromJSON(jsonValue));
    }

    /**
     * Partial update of a team using JSON Patch (RFC 6902). Requires team membership or admin access.
     * Patch a team
     */
    async patchTeam(requestParameters: PatchTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Team> {
        const response = await this.patchTeamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchTeamNote without sending the request
     */
    async patchTeamNoteRequestOpts(requestParameters: PatchTeamNoteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling patchTeamNote().'
            );
        }

        if (requestParameters['teamNoteId'] == null) {
            throw new runtime.RequiredError(
                'teamNoteId',
                'Required parameter "teamNoteId" was null or undefined when calling patchTeamNote().'
            );
        }

        if (requestParameters['jsonPatchDocumentInner'] == null) {
            throw new runtime.RequiredError(
                'jsonPatchDocumentInner',
                'Required parameter "jsonPatchDocumentInner" was null or undefined when calling patchTeamNote().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}/notes/{team_note_id}`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));
        urlPath = urlPath.replace(`{${"team_note_id"}}`, encodeURIComponent(String(requestParameters['teamNoteId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['jsonPatchDocumentInner']!.map(JsonPatchDocumentInnerToJSON),
        };
    }

    /**
     * Apply JSON Patch operations to partially update a team note
     * Partially update a team note
     */
    async patchTeamNoteRaw(requestParameters: PatchTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamNote>> {
        const requestOptions = await this.patchTeamNoteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamNoteFromJSON(jsonValue));
    }

    /**
     * Apply JSON Patch operations to partially update a team note
     * Partially update a team note
     */
    async patchTeamNote(requestParameters: PatchTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamNote> {
        const response = await this.patchTeamNoteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTeam without sending the request
     */
    async updateTeamRequestOpts(requestParameters: UpdateTeamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling updateTeam().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateTeam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Full replacement update of a team. Requires team membership or admin access.
     * Update a team
     */
    async updateTeamRaw(requestParameters: UpdateTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Team>> {
        const requestOptions = await this.updateTeamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamFromJSON(jsonValue));
    }

    /**
     * Full replacement update of a team. Requires team membership or admin access.
     * Update a team
     */
    async updateTeam(requestParameters: UpdateTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Team> {
        const response = await this.updateTeamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTeamMetadata without sending the request
     */
    async updateTeamMetadataRequestOpts(requestParameters: UpdateTeamMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling updateTeamMetadata().'
            );
        }

        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling updateTeamMetadata().'
            );
        }

        if (requestParameters['metadata'] == null) {
            throw new runtime.RequiredError(
                'metadata',
                'Required parameter "metadata" was null or undefined when calling updateTeamMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}/metadata/{key}`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));
        urlPath = urlPath.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MetadataToJSON(requestParameters['metadata']),
        };
    }

    /**
     * Update the value of an existing metadata key for the specified team.
     * Update team metadata
     */
    async updateTeamMetadataRaw(requestParameters: UpdateTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Metadata>> {
        const requestOptions = await this.updateTeamMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataFromJSON(jsonValue));
    }

    /**
     * Update the value of an existing metadata key for the specified team.
     * Update team metadata
     */
    async updateTeamMetadata(requestParameters: UpdateTeamMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Metadata> {
        const response = await this.updateTeamMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTeamNote without sending the request
     */
    async updateTeamNoteRequestOpts(requestParameters: UpdateTeamNoteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling updateTeamNote().'
            );
        }

        if (requestParameters['teamNoteId'] == null) {
            throw new runtime.RequiredError(
                'teamNoteId',
                'Required parameter "teamNoteId" was null or undefined when calling updateTeamNote().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateTeamNote().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{team_id}/notes/{team_note_id}`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));
        urlPath = urlPath.replace(`{${"team_note_id"}}`, encodeURIComponent(String(requestParameters['teamNoteId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Updates a specific note within the team
     * Update a team note
     */
    async updateTeamNoteRaw(requestParameters: UpdateTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamNote>> {
        const requestOptions = await this.updateTeamNoteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamNoteFromJSON(jsonValue));
    }

    /**
     * Updates a specific note within the team
     * Update a team note
     */
    async updateTeamNote(requestParameters: UpdateTeamNoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamNote> {
        const response = await this.updateTeamNoteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
